import { useEffect, useState } from "react";
import { cancelCrmFollowUp, getCrmFollowUps, updateCrmFollowUp } from "../../../api/crmApi";
import { CrmBadge, CrmHeader, CrmPagination, crmInput } from "../../../components/crm/CrmUi";
import EmptyState from "../../../components/dashboard/EmptyState";
import LoadingSkeleton from "../../../components/dashboard/LoadingSkeleton";
import { formatDate } from "../../../utils/dashboardFormatters";

const CrmFollowUps=()=>{const[query,setQuery]=useState({status:"",priority:"",entityType:"",page:1});const[data,setData]=useState(null);const[feedback,setFeedback]=useState("");const[refresh,setRefresh]=useState(0);
useEffect(()=>{let active=true;getCrmFollowUps({...query,status:query.status||undefined,priority:query.priority||undefined,entityType:query.entityType||undefined,limit:30}).then((result)=>active&&setData(result)).catch((error)=>active&&setFeedback(error.response?.data?.message||"Unable to load follow-ups."));return()=>{active=false;};},[query,refresh]);
const action=async(operation,message)=>{try{await operation();setFeedback(message);setRefresh((value)=>value+1);}catch(error){setFeedback(error.response?.data?.message||"Unable to update follow-up.");}};
return <div className="space-y-6"><CrmHeader title="CRM follow-ups" description="Upcoming, overdue, completed, and cancelled relationship tasks." />{feedback&&<p className="rounded-xl bg-blue-50 p-3 text-sm text-blue-800">{feedback}</p>}<div className="grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-3"><select value={query.status} onChange={(event)=>setQuery({...query,status:event.target.value,page:1})} className={crmInput}><option value="">All statuses</option><option>pending</option><option>overdue</option><option>completed</option><option>cancelled</option></select><select value={query.priority} onChange={(event)=>setQuery({...query,priority:event.target.value,page:1})} className={crmInput}><option value="">All priorities</option>{["low","medium","high","urgent"].map((value)=><option key={value}>{value}</option>)}</select><select value={query.entityType} onChange={(event)=>setQuery({...query,entityType:event.target.value,page:1})} className={crmInput}><option value="">All entity types</option>{["customer","partner","expert","lead","ticket","application"].map((value)=><option key={value}>{value}</option>)}</select></div>{!data?<LoadingSkeleton count={7}/>:!data.items.length?<EmptyState title="No follow-ups" description="Schedule a follow-up from any CRM detail page."/>:<><div className="grid gap-4 lg:grid-cols-2">{data.items.map((item)=><article key={item._id} className={`rounded-2xl border p-5 shadow-sm ${item.isOverdue?"border-rose-200 bg-rose-50":"bg-white"}`}><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{item.title}</h2><p className="mt-1 text-xs text-slate-500">{item.relatedEntityType}: {item.relatedEntityId}</p></div><div className="flex gap-2"><CrmBadge value={item.isOverdue?"urgent":item.status}/><CrmBadge value={item.priority}/></div></div><p className="mt-3 text-sm text-slate-600">{item.description}</p><p className="mt-3 text-sm font-semibold">Due {formatDate(item.dueAt)}</p>{item.status==="pending"&&<div className="mt-4 flex gap-3"><button onClick={()=>action(()=>updateCrmFollowUp(item._id,{status:"completed",outcome:"Completed by administrator"}),"Follow-up completed.")} className="text-sm font-semibold text-emerald-700">Complete</button><button onClick={()=>action(()=>cancelCrmFollowUp(item._id),"Follow-up cancelled.")} className="text-sm font-semibold text-rose-700">Cancel</button></div>}</article>)}</div><CrmPagination pagination={data.pagination} onPage={(page)=>setQuery({...query,page})}/></>}</div>};
export default CrmFollowUps;
