import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getCrmOverview } from "../../../api/crmApi";
import EmptyState from "../../../components/dashboard/EmptyState";
import LoadingSkeleton from "../../../components/dashboard/LoadingSkeleton";
import StatCard from "../../../components/dashboard/StatCard";
import { formatDate } from "../../../utils/dashboardFormatters";
import { CrmBadge, CrmHeader } from "../../../components/crm/CrmUi";

const CrmOverview = () => {
  const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; getCrmOverview().then((result) => active && setData(result)).catch((requestError) => active && setError(requestError.response?.data?.message || "Unable to load CRM overview.")); return () => { active = false; }; }, []);
  if (error) return <EmptyState title="CRM overview unavailable" description={error}/>;
  if (!data) return <LoadingSkeleton count={8}/>;
  const stats = [["Customers",data.summary.totalCustomers],["Active partners",data.summary.activePartners],["Active experts",data.summary.activeExperts],["Open leads",data.summary.openLeads],["Lead follow-ups",data.summary.leadsRequiringFollowUp],["Open tickets",data.summary.openTickets],["Overdue",data.summary.overdueFollowUps],["Communications",data.summary.recentCommunications]];
  return <div className="space-y-7"><CrmHeader title="CRM overview" description="Customer relationships, support workload, and next actions from live data."/><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([title,value]) => <StatCard key={title} title={title} value={value}/>)}</section><section className="grid gap-6 xl:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Overdue follow-ups</h2><div className="mt-4 space-y-3">{data.overdueFollowUps.length ? data.overdueFollowUps.map((item) => <Link key={item._id} to="/admin/crm/follow-ups" className="block rounded-xl bg-rose-50 p-3"><div className="flex justify-between gap-3"><strong className="text-sm">{item.title}</strong><CrmBadge value={item.priority}/></div><p className="mt-1 text-xs text-slate-500">{item.relatedEntityType}: {item.relatedEntityId} · {formatDate(item.dueAt)}</p></Link>) : <p className="text-sm text-slate-500">No overdue work.</p>}</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Upcoming follow-ups</h2><div className="mt-4 space-y-3">{data.upcomingFollowUps.length ? data.upcomingFollowUps.map((item) => <Link key={item._id} to="/admin/crm/follow-ups" className="block rounded-xl bg-slate-50 p-3"><strong className="text-sm">{item.title}</strong><p className="mt-1 text-xs text-slate-500">{item.relatedEntityType}: {item.relatedEntityId} · {formatDate(item.dueAt)}</p></Link>) : <p className="text-sm text-slate-500">Nothing scheduled for the next seven days.</p>}</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Recently added leads</h2><div className="mt-4 space-y-3">{data.recentLeads.map((item) => <Link key={item._id} to={`/admin/crm/leads/${item._id}`} className="flex justify-between rounded-xl bg-slate-50 p-3"><span><strong className="block text-sm">{item.name}</strong><span className="text-xs text-slate-500">{item.leadNumber}</span></span><CrmBadge value={item.status}/></Link>)}</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Recently updated tickets</h2><div className="mt-4 space-y-3">{data.recentTickets.map((item) => <Link key={item._id} to={`/admin/crm/tickets/${item._id}`} className="flex justify-between rounded-xl bg-slate-50 p-3"><span><strong className="block text-sm">{item.subject}</strong><span className="text-xs text-slate-500">{item.ticketNumber}</span></span><CrmBadge value={item.status}/></Link>)}</div></div></section>{data.recentActivity.length > 0 && <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Recent internal activity</h2><div className="mt-4 divide-y">{data.recentActivity.map((item) => <div key={item._id} className="py-3"><p className="text-sm font-semibold">{item.summary}</p><p className="text-xs text-slate-500">{item.actorUserId} · {formatDate(item.createdAt)}</p></div>)}</div></section>}</div>;
};
export default CrmOverview;
