import { Copy, Download, FileText, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { claimReferral, getDeclarationForms, getPaymentHistory, getReferrals, getRenewal, getRewards, getSoftware, requestRenewal } from "../../api/dashboardApi";
import EmptyState from "../../components/dashboard/EmptyState";
import LoadingSkeleton from "../../components/dashboard/LoadingSkeleton";
import { formatDate } from "../../utils/dashboardFormatters";

const Page = ({ title, description, children }) => <div className="space-y-6"><header><h1 className="text-2xl font-bold">{title}</h1><p className="mt-1 text-slate-500">{description}</p></header>{children}</div>;
const ErrorState = ({ message }) => <EmptyState title="Unable to load this page" description={message} />;

const useLoad = (request) => { const [data, setData] = useState(null); const [error, setError] = useState(""); useEffect(() => { let active = true; request().then((result) => active && setData(result)).catch((requestError) => active && setError(requestError.response?.data?.message || "Unable to load records.")); return () => { active = false; }; }, [request]); return { data, error, setData, setError }; };

export const SoftwarePage = () => {
  const { data, error } = useLoad(getSoftware);
  return <Page title="Software" description="Downloads published and approved by Karlo Services administrators.">{error ? <ErrorState message={error} /> : !data ? <LoadingSkeleton count={4} /> : !data.software.length ? <EmptyState title="No software available" description="No approved software downloads have been published." /> : <div className="grid gap-4 md:grid-cols-2">{data.software.map((item) => <article key={item._id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex gap-4"><span className="text-3xl">{item.icon || "💻"}</span><div><h2 className="font-bold">{item.name}</h2><p className="text-xs text-slate-500">{[item.version, item.fileSize, item.operatingSystem].filter(Boolean).join(" · ")}</p></div></div><p className="mt-4 text-sm leading-6 text-slate-600">{item.description}</p>{item.installationGuide && <p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{item.installationGuide}</p>}<a href={item.downloadUrl} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white"><Download size={17} /> Download</a></article>)}</div>}</Page>;
};

export const DeclarationFormsPage = () => {
  const { data, error } = useLoad(getDeclarationForms);
  return <Page title="Declaration forms" description="Verified declaration documents managed by Karlo Services.">{error ? <ErrorState message={error} /> : !data ? <LoadingSkeleton count={4} /> : !data.forms.length ? <EmptyState title="No declaration forms available" description="No forms have been uploaded by an administrator." /> : <div className="grid gap-4 md:grid-cols-2">{data.forms.map((item) => <article key={item._id} className="rounded-2xl border bg-white p-5 shadow-sm"><FileText className="text-blue-700" /><h2 className="mt-3 font-bold">{item.title}</h2><p className="mt-1 text-xs text-slate-500">{[item.category, item.language, item.version, item.fileSize].filter(Boolean).join(" · ")}</p><p className="mt-3 text-sm leading-6 text-slate-600">{item.description}</p><a href={item.fileUrl} target="_blank" rel="noopener noreferrer" download={item.fileName} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-blue-700 px-4 py-2.5 text-sm font-semibold text-blue-700"><Download size={17} /> Download {item.fileName}</a></article>)}</div>}</Page>;
};

export const PaymentHistoryPage = () => {
  const { data, error } = useLoad(getPaymentHistory);
  return <Page title="Payment history" description="Only payment records associated with your authenticated account are shown.">{error ? <ErrorState message={error} /> : !data ? <LoadingSkeleton count={5} /> : !data.payments.length ? <EmptyState title="No payment records found" description="Real payments will appear here after they are recorded." /> : <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Transaction</th><th className="p-4">Type</th><th className="p-4">Amount</th><th className="p-4">Status</th><th className="p-4">Method</th><th className="p-4">Date</th></tr></thead><tbody className="divide-y">{data.payments.map((item) => <tr key={item._id}><td className="p-4 font-semibold">{item.transactionId}</td><td className="p-4">{item.type.replaceAll("_", " ")}</td><td className="p-4">₹{item.amount.toLocaleString("en-IN")}</td><td className="p-4 capitalize">{item.status}</td><td className="p-4">{item.paymentMethod || "—"}</td><td className="p-4">{formatDate(item.paidAt || item.createdAt)}</td></tr>)}</tbody></table></div>}</Page>;
};

export const RewardsPage = () => {
  const { data, error } = useLoad(getRewards);
  return <Page title="Rewards" description="Real reward and cashback records for your account.">{error ? <ErrorState message={error} /> : !data ? <LoadingSkeleton count={4} /> : <><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Approved rewards</p><p className="mt-2 text-2xl font-bold">₹{data.summary.approved.toLocaleString("en-IN")}</p></article><article className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Pending rewards</p><p className="mt-2 text-2xl font-bold">₹{data.summary.pending.toLocaleString("en-IN")}</p></article></div>{!data.rewards.length ? <EmptyState title="No reward records found" description="Eligible rewards will appear after their completion conditions are verified." /> : <div className="space-y-3">{data.rewards.map((item) => <article key={item._id} className="flex flex-col justify-between gap-3 rounded-2xl border bg-white p-5 sm:flex-row"><div><h2 className="font-bold capitalize">{item.rewardType}</h2><p className="mt-1 text-sm text-slate-500">{item.description || item.source}</p></div><div className="sm:text-right"><p className="font-bold">₹{item.amount.toLocaleString("en-IN")}</p><p className="text-xs capitalize text-slate-500">{item.status} · {formatDate(item.createdAt)}</p></div></article>)}</div>}</>}</Page>;
};

export const ReferEarnPage = () => {
  const { data, error, setData, setError } = useLoad(getReferrals); const [code, setCode] = useState(""); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState("");
  const claim = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { await claimReferral(code); setFeedback("Referral claimed successfully."); setCode(""); setData(await getReferrals()); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to claim referral."); } finally { setBusy(false); } };
  const referralLink = data ? `${window.location.origin}/register?ref=${encodeURIComponent(data.account.referralCode)}` : "";
  const copy = async () => { await navigator.clipboard.writeText(referralLink); setFeedback("Shareable referral link copied."); };
  return <Page title="Refer & Earn" description="Share your unique code. Rewards are recorded only after configured completion conditions are met.">{error ? <ErrorState message={error} /> : !data ? <LoadingSkeleton count={4} /> : <><section className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-sm text-slate-500">Your referral code</p><div className="mt-2 flex flex-wrap items-center gap-3"><code className="rounded-xl bg-slate-100 px-4 py-3 text-xl font-bold text-blue-700">{data.account.referralCode}</code><button type="button" onClick={copy} className="inline-flex items-center gap-2 rounded-xl border px-4 py-3 font-semibold"><Copy size={17} /> Copy</button></div>{feedback && <p className="mt-3 text-sm text-emerald-700">{feedback}</p>}</section><section className="grid gap-4 sm:grid-cols-4">{[["Total referrals", data.summary.total], ["Successful", data.summary.successful], ["Pending", data.summary.pending], ["Earned rewards", `₹${data.summary.earned}`]].map(([label, value]) => <article key={label} className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></article>)}</section><form onSubmit={claim} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Claim a referral</h2><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input required value={code} onChange={(event) => setCode(event.target.value)} placeholder="Referral code" className="min-w-0 flex-1 rounded-xl border px-4 py-2.5 uppercase" /><button disabled={busy} className="rounded-xl bg-blue-700 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{busy ? "Claiming…" : "Claim code"}</button></div></form>{!data.referrals.length && <EmptyState title="No referrals yet" description="Share your code to begin building a real referral history." />}</>}</Page>;
};

export const PartnerRenewalPage = () => {
  const { data, error, setData, setError } = useLoad(getRenewal); const [busy, setBusy] = useState(false);
  const request = async () => { setBusy(true); setError(""); try { await requestRenewal(); setData(await getRenewal()); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to request renewal."); } finally { setBusy(false); } };
  return <Page title="Partner renewal" description="Review registration validity and submit a renewal request when eligible.">{error ? <ErrorState message={error} /> : !data ? <LoadingSkeleton count={4} /> : <><section className="grid gap-4 sm:grid-cols-3">{[["Registered", formatDate(data.registration.registeredAt)], ["Current expiry", formatDate(data.registration.expiresAt)], ["Status", data.registration.status.replaceAll("_", " ")]].map(([label, value]) => <article key={label} className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 font-bold capitalize">{value}</p></article>)}</section><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Renewal configuration</h2>{!data.config.enabled || data.config.renewalFee === null ? <p className="mt-3 text-sm text-amber-700">Online renewal is not currently configured by an administrator.</p> : <><p className="mt-3 text-sm text-slate-600">Period: {data.config.periodMonths} months · Fee: ₹{data.config.renewalFee.toLocaleString("en-IN")} · Grace: {data.config.graceDays} days</p><button type="button" disabled={!data.eligible || busy} onClick={request} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-blue-700 px-5 py-2.5 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40"><RefreshCw size={17} /> {busy ? "Submitting…" : "Request renewal"}</button></>}</section>{!data.history.length ? <EmptyState title="No previous renewals" description="Renewal requests and decisions will appear here." /> : <div className="space-y-3">{data.history.map((item) => <article key={item._id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><p className="font-bold capitalize">{item.status}</p><p>₹{item.fee.toLocaleString("en-IN")}</p></div><p className="mt-2 text-sm text-slate-500">{formatDate(item.periodStart)} – {formatDate(item.periodEnd)}</p></article>)}</div>}</>}</Page>;
};
