import mongoose from "mongoose";
const imageSchema = new mongoose.Schema({ url: { type: String, trim: true, default: "" }, publicId: { type: String, trim: true, default: "" }, altText: { type: String, trim: true, maxlength: 160, default: "" } }, { _id: false });
const footerLinkSchema = new mongoose.Schema({ label: { type: String, required: true, trim: true, maxlength: 100 }, url: { type: String, required: true, trim: true, maxlength: 500 }, isExternal: { type: Boolean, default: false }, isActive: { type: Boolean, default: true }, displayOrder: { type: Number, min: 0, default: 0 } }, { _id: false });
const footerSectionSchema = new mongoose.Schema({ title: { type: String, required: true, trim: true, maxlength: 100 }, isActive: { type: Boolean, default: true }, displayOrder: { type: Number, min: 0, default: 0 }, links: { type: [footerLinkSchema], default: [] } }, { _id: false });
const siteSettingsSchema = new mongoose.Schema({
  key: { type: String, unique: true, immutable: true, default: "main-settings" }, siteName: { type: String, trim: true, maxlength: 120, default: "Karlo Services" }, logo: { type: imageSchema, default: () => ({}) },
  shortSiteName: { type: String, trim: true, maxlength: 60, default: "Karlo" }, tagline: { type: String, trim: true, maxlength: 240, default: "" },
  general: { defaultCurrency: { type: String, trim: true, maxlength: 10, default: "INR" }, defaultLanguage: { type: String, trim: true, maxlength: 30, default: "English" }, maintenanceMode: { type: Boolean, default: false }, registrationAvailable: { type: Boolean, default: true }, defaultPaginationSize: { type: Number, min: 5, max: 100, default: 20 }, announcementBar: { type: String, trim: true, maxlength: 300, default: "" } },
  contact: { phone: { type: String, trim: true, default: "" }, alternatePhone: { type: String, trim: true, default: "" }, email: { type: String, trim: true, lowercase: true, default: "" }, salesEmail: { type: String, trim: true, lowercase: true, default: "" }, supportEmail: { type: String, trim: true, lowercase: true, default: "" }, whatsapp: { type: String, trim: true, default: "" }, address: { type: String, trim: true, maxlength: 500, default: "" }, city: { type: String, trim: true, default: "" }, state: { type: String, trim: true, default: "" }, pincode: { type: String, trim: true, default: "" }, workingHours: { type: String, trim: true, maxlength: 160, default: "" }, mapUrl: { type: String, trim: true, maxlength: 500, default: "" }, supportText: { type: String, trim: true, maxlength: 500, default: "" } },
  socialLinks: { facebook: { type: String, default: "" }, instagram: { type: String, default: "" }, youtube: { type: String, default: "" }, linkedin: { type: String, default: "" }, twitter: { type: String, default: "" } },
  footer: { shortDescription: { type: String, trim: true, maxlength: 500, default: "" }, copyrightText: { type: String, trim: true, maxlength: 200, default: "" }, supportText: { type: String, trim: true, maxlength: 300, default: "" } },
  footerSections: { type: [footerSectionSchema], default: [] },
  legal: { serviceDisclaimer: { type: String, trim: true, maxlength: 1200, default: "" }, refundDisclaimer: { type: String, trim: true, maxlength: 1200, default: "" } },
  seo: { defaultTitle: { type: String, trim: true, maxlength: 180, default: "" }, titleTemplate: { type: String, trim: true, maxlength: 180, default: "%s | Karlo Services" }, defaultDescription: { type: String, trim: true, maxlength: 500, default: "" }, defaultKeywords: { type: [String], default: [] }, defaultImage: { type: imageSchema, default: () => ({}) }, siteUrl: { type: String, trim: true, maxlength: 500, default: "" }, twitterCardType: { type: String, enum: ["summary", "summary_large_image"], default: "summary_large_image" } },
}, { timestamps: true, collection: "sitesettings" });
export const SiteSettings = mongoose.model("SiteSettings", siteSettingsSchema);
