import { Search, Star } from "lucide-react";
import { useEffect, useState } from "react";
import { getPublicFaqs } from "../../api/publicCmsApi";
import FaqAccordion from "./FaqAccordion";

const FaqBrowser = ({ audience = "public", compact = false }) => {
  const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; const timer = setTimeout(() => { getPublicFaqs({ audience, limit: 100, ...(search.trim() ? { search: search.trim() } : {}), ...(category ? { category } : {}) }).then((result) => { if (active) { setData(result.data); setError(""); } }).catch((requestError) => active && setError(requestError.response?.data?.message || "Unable to load FAQs.")); }, 250); return () => { active = false; clearTimeout(timer); }; }, [audience, category, search]);
  const items = data?.items || []; const showFeatured = !search.trim() && !category && data?.featured?.length > 0;
  return <section className={compact ? "rounded-2xl border bg-white p-5 shadow-sm" : ""}><div className="flex items-center gap-2"><Search className="text-blue-700" /><h2 className="text-xl font-bold">Search FAQs</h2></div><label className="relative mt-4 block"><span className="sr-only">Search FAQs by question, answer, keyword, or category</span><Search className="absolute left-4 top-4 text-slate-400" size={20} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search questions, answers, keywords, or categories" className="min-h-14 w-full rounded-xl border border-slate-300 bg-white py-3 pl-12 pr-4 text-base focus:border-blue-600 focus:outline-none focus:ring-4 focus:ring-blue-100" /></label><div className="mt-4 flex gap-2 overflow-x-auto pb-2" aria-label="FAQ categories"><button type="button" onClick={() => setCategory("")} aria-pressed={!category} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold ${!category ? "bg-blue-700 text-white" : "border bg-white text-slate-700"}`}>All</button>{(data?.categories || []).map((item) => <button key={item} type="button" onClick={() => setCategory(item)} aria-pressed={category === item} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold ${category === item ? "bg-blue-700 text-white" : "border bg-white text-slate-700"}`}>{item}</button>)}</div>{error && <p role="alert" className="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}{!data && !error && <p className="mt-5 text-sm text-slate-500">Loading frequently asked questions…</p>}{showFeatured && <section className="mt-7"><h3 className="flex items-center gap-2 text-lg font-bold"><Star className="fill-amber-400 text-amber-500" size={20} /> Popular Questions</h3><div className="mt-3"><FaqAccordion items={data.featured} /></div></section>}<section className="mt-7"><h3 className="text-lg font-bold">{search || category ? "Matching Questions" : "All Questions"}</h3>{data && !items.length ? <p className="mt-3 rounded-xl bg-slate-50 p-5 text-slate-600">No FAQs match your search. Try another keyword or contact support.</p> : <div className="mt-3"><FaqAccordion items={items} /></div>}</section></section>;
};

export default FaqBrowser;
