import { useEffect, useState } from "react"; import { getAdminServices } from "../../../api/adminApi"; import { getHomepageAdminContent, publishHomepage, updateFeaturedServices, updateHomepageHero, updateHomepageSections } from "../../../api/adminCmsApi"; import ConfirmDialog from "../../../components/dashboard/ConfirmDialog"; import LoadingSkeleton from "../../../components/dashboard/LoadingSkeleton";
const HomepageEditor = () => { const [page,setPage]=useState(null), [services,setServices]=useState([]), [image,setImage]=useState(null), [busy,setBusy]=useState(false), [confirm,setConfirm]=useState(false), [feedback,setFeedback]=useState("");
  useEffect(() => { Promise.all([getHomepageAdminContent(), getAdminServices({ limit: 100 })]).then(([cms, serviceData]) => { setPage(cms.data.homepage); setServices(serviceData.services || []); }).catch((error) => setFeedback(error.response?.data?.message || "Unable to load homepage content.")); }, []); const hero = page?.hero;
  const saveHero = async (event) => { event.preventDefault(); setBusy(true); try { let result = await updateHomepageHero({ heading: hero.heading, subheading: hero.subheading, primaryButton: hero.primaryButton, secondaryButton: hero.secondaryButton, isActive: hero.isActive }); if (image) { const form = new FormData(); form.append("image", image); result = await updateHomepageHero(form); } setPage(result.data.homepage); setImage(null); setFeedback("Hero saved as draft."); } catch(error) { setFeedback(error.response?.data?.message || "Unable to save hero."); } finally { setBusy(false); } };
  const saveFeatured = async () => { setBusy(true); try { const result = await updateFeaturedServices(page.featuredServiceIds.map((value) => typeof value === "string" ? value : value._id)); setPage(result.data.homepage); setFeedback("Featured services saved as draft."); } catch(error) { setFeedback(error.response?.data?.message || "Unable to save featured services."); } finally { setBusy(false); } };
  const saveSections = async () => { setBusy(true); try { const result = await updateHomepageSections({ sectionVisibility: page.sectionVisibility, sectionOrder: page.sectionOrder }); setPage(result.data.homepage); setFeedback("Section settings saved as draft."); } catch(error) { setFeedback(error.response?.data?.message || "Unable to save section settings."); } finally { setBusy(false); } };
  const move = (index, amount) => { const next=[...page.sectionOrder], target=index+amount; if(target<0||target>=next.length)return; [next[index],next[target]]=[next[target],next[index]]; setPage({...page,sectionOrder:next}); };
  if (!page) return <><LoadingSkeleton count={5}/>{feedback && <p className="text-red-700">{feedback}</p>}</>;
  return <div className="space-y-6">{feedback && <p role="status" className="rounded-xl bg-blue-50 p-3 text-sm text-blue-800">{feedback}</p>}<div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-4"><div><strong>Status: {page.status}</strong><p className="text-sm text-slate-500">Last updated {new Date(page.updatedAt).toLocaleString()}</p></div><button type="button" onClick={()=>setConfirm(true)} className="rounded-xl bg-emerald-700 px-5 py-2.5 font-semibold text-white">Publish homepage</button></div>
  <form onSubmit={saveHero} className="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-2"><h2 className="text-xl font-bold md:col-span-2">Hero</h2>{[["Heading","heading"],["Subheading","subheading"],["Primary button text","primaryButton.text"],["Primary button link","primaryButton.link"],["Secondary button text","secondaryButton.text"],["Secondary button link","secondaryButton.link"]].map(([label,path]) => { const [group,key]=path.split("."); const value=key?hero[group]?.[key]:hero[group]; return <label key={path} className="text-sm font-semibold">{label}<input value={value||""} onChange={(e)=>setPage({...page,hero:key?{...hero,[group]:{...hero[group],[key]:e.target.value}}:{...hero,[group]:e.target.value}})} className="mt-1 w-full rounded-lg border p-2.5"/></label>; })}<label className="text-sm font-semibold">Hero image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e)=>setImage(e.target.files[0]||null)} className="mt-1 block w-full"/></label>{(image||hero.image?.url)&&<img src={image?URL.createObjectURL(image):hero.image.url} alt="Hero preview" className="h-32 w-full rounded-xl object-cover"/>}<label className="flex items-center gap-2"><input type="checkbox" checked={hero.isActive} onChange={(e)=>setPage({...page,hero:{...hero,isActive:e.target.checked}})}/> Show hero</label><button disabled={busy} className="rounded-xl bg-blue-700 px-4 py-2.5 font-semibold text-white md:col-span-2">Save hero draft</button></form>
  <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Featured services</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{services.map((service)=>{const ids=page.featuredServiceIds.map((value)=>String(value._id||value)), checked=ids.includes(String(service._id)); return <label key={service._id} className="flex items-center gap-2 rounded-lg border p-3"><input type="checkbox" checked={checked} onChange={()=>setPage({...page,featuredServiceIds:checked?ids.filter((value)=>value!==String(service._id)):[...ids,String(service._id)]})}/>{service.title}</label>;})}</div><button type="button" disabled={busy} onClick={saveFeatured} className="mt-4 rounded-xl bg-blue-700 px-4 py-2.5 font-semibold text-white">Save selection</button></section>
  <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Sections</h2><div className="mt-4 space-y-2">{page.sectionOrder.map((name,index)=><div key={name} className="flex items-center justify-between rounded-lg border p-3"><label className="flex items-center gap-2"><input type="checkbox" checked={page.sectionVisibility[name]!==false} onChange={(e)=>setPage({...page,sectionVisibility:{...page.sectionVisibility,[name]:e.target.checked}})}/>{name}</label><span><button type="button" aria-label={`Move ${name} up`} onClick={()=>move(index,-1)} className="px-2">↑</button><button type="button" aria-label={`Move ${name} down`} onClick={()=>move(index,1)} className="px-2">↓</button></span></div>)}</div><button type="button" disabled={busy} onClick={saveSections} className="mt-4 rounded-xl bg-blue-700 px-4 py-2.5 font-semibold text-white">Save section settings</button></section>
  <ConfirmDialog open={confirm} title="Publish homepage?" description="All saved homepage draft changes will become public." busy={busy} confirmLabel="Publish" onCancel={()=>setConfirm(false)} onConfirm={async()=>{setBusy(true);try{const result=await publishHomepage();setPage(result.data.homepage);setFeedback("Homepage published.");setConfirm(false);}catch(error){setFeedback(error.response?.data?.message||"Unable to publish.");}finally{setBusy(false);}}}/></div>;
}; export default HomepageEditor;
