import { useState } from "react";
import { createCrmCommunication, createCrmFollowUp, createCrmNote, deleteCrmNote, updateCrmFollowUp } from "../../api/crmApi";
import { formatDate } from "../../utils/dashboardFormatters";
import { CrmBadge, crmInput } from "./CrmUi";

const nowLocal = () => new Date(Date.now() + 60 * 60 * 1000).toISOString().slice(0, 16);

const CrmActivityPanels = ({ entityType, entityId, data, onRefresh }) => {
  const [note, setNote] = useState("");
  const [followUp, setFollowUp] = useState({ title: "", description: "", dueAt: nowLocal(), priority: "medium", assignedTo: "" });
  const [communication, setCommunication] = useState({ communicationType: "phone", direction: "outbound", subject: "", summary: "", contactValue: "", occurredAt: new Date().toISOString().slice(0, 16), outcome: "", nextAction: "" });
  const [feedback, setFeedback] = useState("");
  const execute = async (operation, success) => { try { await operation(); setFeedback(success); await onRefresh(); } catch (error) { setFeedback(error.response?.data?.message || "Unable to save CRM activity."); } };
  return <div className="space-y-6">
    {feedback && <p className="rounded-xl bg-blue-50 px-4 py-3 text-sm text-blue-800">{feedback}</p>}
    <section className="grid gap-6 xl:grid-cols-3">
      <form onSubmit={(event) => { event.preventDefault(); execute(() => createCrmNote(entityType, entityId, { content: note }), "Internal note added."); setNote(""); }} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Internal note</h2><textarea required rows="5" value={note} onChange={(event) => setNote(event.target.value)} className={crmInput} placeholder="Visible only to administrators" /><button className="mt-3 rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white">Add note</button></form>
      <form onSubmit={(event) => { event.preventDefault(); execute(() => createCrmFollowUp({ ...followUp, relatedEntityType: entityType, relatedEntityId: entityId }), "Follow-up scheduled."); setFollowUp({ ...followUp, title: "", description: "" }); }} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Schedule follow-up</h2><input required value={followUp.title} onChange={(event) => setFollowUp({ ...followUp, title: event.target.value })} className={crmInput} placeholder="Title" /><input required type="datetime-local" value={followUp.dueAt} onChange={(event) => setFollowUp({ ...followUp, dueAt: event.target.value })} className={crmInput} /><select value={followUp.priority} onChange={(event) => setFollowUp({ ...followUp, priority: event.target.value })} className={crmInput}>{["low","medium","high","urgent"].map((value) => <option key={value}>{value}</option>)}</select><button className="mt-3 rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white">Schedule</button></form>
      <form onSubmit={(event) => { event.preventDefault(); execute(() => createCrmCommunication(entityType, entityId, communication), "Communication logged."); setCommunication({ ...communication, subject: "", summary: "", outcome: "", nextAction: "" }); }} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Log communication</h2><div className="grid grid-cols-2 gap-2"><select value={communication.communicationType} onChange={(event) => setCommunication({ ...communication, communicationType: event.target.value })} className={crmInput}>{["phone","email","whatsapp","sms","meeting","in_person","other"].map((value) => <option key={value}>{value}</option>)}</select><select value={communication.direction} onChange={(event) => setCommunication({ ...communication, direction: event.target.value })} className={crmInput}><option>outbound</option><option>inbound</option></select></div><input value={communication.subject} onChange={(event) => setCommunication({ ...communication, subject: event.target.value })} className={crmInput} placeholder="Subject" /><textarea required rows="3" value={communication.summary} onChange={(event) => setCommunication({ ...communication, summary: event.target.value })} className={crmInput} placeholder="Summary" /><button className="mt-3 rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white">Log activity</button></form>
    </section>
    <section className="grid gap-6 xl:grid-cols-3">
      <div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Private notes</h2><div className="mt-4 space-y-3">{data.notes?.length ? data.notes.map((item) => <article key={item._id} className="rounded-xl bg-slate-50 p-3"><p className="whitespace-pre-wrap text-sm">{item.content}</p><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{item.createdBy} · {formatDate(item.createdAt)}</span><button onClick={() => execute(() => deleteCrmNote(item._id), "Note deleted.")} className="text-rose-700">Delete</button></div></article>) : <p className="text-sm text-slate-500">No notes yet.</p>}</div></div>
      <div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Follow-ups</h2><div className="mt-4 space-y-3">{data.followUps?.length ? data.followUps.map((item) => <article key={item._id} className={`rounded-xl p-3 ${item.isOverdue ? "bg-rose-50" : "bg-slate-50"}`}><div className="flex justify-between gap-2"><strong className="text-sm">{item.title}</strong><CrmBadge value={item.isOverdue ? "urgent" : item.status}/></div><p className="mt-1 text-xs text-slate-500">Due {formatDate(item.dueAt)}</p>{item.status === "pending" && <button onClick={() => execute(() => updateCrmFollowUp(item._id, { status: "completed", outcome: "Completed by administrator" }), "Follow-up completed.")} className="mt-2 text-xs font-semibold text-emerald-700">Mark complete</button>}</article>) : <p className="text-sm text-slate-500">No follow-ups yet.</p>}</div></div>
      <div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Communication history</h2><div className="mt-4 space-y-3">{data.communications?.length ? data.communications.map((item) => <article key={item._id} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between text-xs font-semibold uppercase text-blue-700"><span>{item.communicationType}</span><span>{item.direction}</span></div><p className="mt-2 text-sm">{item.summary}</p><p className="mt-2 text-xs text-slate-500">{item.createdBy} · {formatDate(item.occurredAt)}</p></article>) : <p className="text-sm text-slate-500">No communication logged.</p>}</div></div>
    </section>
    {data.activity?.length > 0 && <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Activity timeline</h2><div className="mt-4 space-y-3">{data.activity.map((item) => <article key={item._id} className="border-l-2 border-blue-200 pl-4"><p className="text-sm font-semibold">{item.summary}</p><p className="text-xs text-slate-500">{item.actorUserId} · {formatDate(item.createdAt)}</p></article>)}</div></section>}
  </div>;
};

export default CrmActivityPanels;
