import API from "./axiosInstance";

const getData = (request) => request.then((response) => response.data);

export const getAdminDashboardSummary = () => getData(API.get("/admin/dashboard-summary"));
export const getAdminApplications = (params = {}) => getData(API.get("/admin/applications", { params }));
export const getAdminApplicationById = (id) => getData(API.get(`/admin/applications/${encodeURIComponent(id)}`));
export const assignApplication = (id, data) => getData(API.patch(`/admin/applications/${encodeURIComponent(id)}/assign`, data));
export const assignRetailer = (id, data) => assignApplication(id, { assignmentType: "expert", assignedExpertId: data.retailerId, remarks: data.remarks });
export const updateApplicationStatus = (id, data) => getData(API.patch(`/admin/applications/${encodeURIComponent(id)}/status`, data));
export const addApplicationRemark = (id, data) => getData(API.post(`/admin/applications/${encodeURIComponent(id)}/remarks`, data));
export const requestApplicationDocuments = (id, data) => getData(API.post(`/admin/applications/${encodeURIComponent(id)}/request-documents`, data));
export const publishApplicationLead = (id, data) => getData(API.post(`/admin/applications/${encodeURIComponent(id)}/publish-lead`, data));
export const getAdminCustomers = (params = {}) => getData(API.get("/admin/customers", { params }));
export const getAdminCustomer = (id) => getData(API.get(`/admin/customers/${encodeURIComponent(id)}`));
export const getAdminRetailers = (params = {}) => getData(API.get("/admin/retailers", { params }));
export const createRetailer = (data) => getData(API.post("/admin/retailers", data));
export const updateRetailer = (id, data) => getData(API.patch(`/admin/retailers/${encodeURIComponent(id)}`, data));
export const getAdminExperts = (params = {}) => getData(API.get("/admin/experts", { params }));
export const createExpert = (data) => getData(API.post("/admin/experts", data));
export const updateExpert = (id, data) => getData(API.patch(`/admin/experts/${encodeURIComponent(id)}`, data));
export const getAdminPartners = (params = {}) => getData(API.get("/admin/partners", { params }));
export const getAdminPartner = (id) => getData(API.get(`/admin/partners/${encodeURIComponent(id)}`));
export const updateAdminPartner = (id, data) => getData(API.patch(`/admin/partners/${encodeURIComponent(id)}`, data));
export const updatePartnerVerification = (id, verificationStatus) => getData(API.patch(`/admin/partners/${encodeURIComponent(id)}/verification`, { verificationStatus }));
export const getAdminServices = (params = {}) => getData(API.get("/admin/services", { params }));
export const createService = (data) => getData(API.post("/admin/services", data));
export const getAdminService = (id) => getData(API.get(`/admin/services/${encodeURIComponent(id)}`));
export const updateService = (id, data) => getData(API.patch(`/admin/services/${encodeURIComponent(id)}`, data));
export const updateServiceStatus = (id, data) => getData(API.patch(`/admin/services/${encodeURIComponent(id)}/status`, data));
export const getServiceForm = (id) => getData(API.get(`/admin/services/${encodeURIComponent(id)}/form`));
export const updateServiceForm = (id, data) => getData(API.put(`/admin/services/${encodeURIComponent(id)}/form`, data));
export const getAdminReports = () => getData(API.get("/admin/reports/summary"));
export const getAdminAssignments = (params = {}) => getData(API.get("/admin/assignments", { params }));
export const getAdminLeads = (params = {}) => getData(API.get("/admin/leads", { params }));
export const getAdminLead = (id) => getData(API.get(`/admin/leads/${encodeURIComponent(id)}`));
export const createAdminLead = (data) => getData(API.post("/admin/leads", data));
export const updateAdminLead = (id, data) => getData(API.patch(`/admin/leads/${encodeURIComponent(id)}`, data));
export const assignAdminLead = (id, partnerUserId) => getData(API.post(`/admin/leads/${encodeURIComponent(id)}/assign`, { partnerUserId }));
export const getAdminContent = (params = {}) => getData(API.get("/admin/content", { params }));
export const createAdminContent = (data) => getData(API.post("/admin/content", data));
export const updateAdminContent = (id, data) => getData(API.patch(`/admin/content/${encodeURIComponent(id)}`, data));
export const getAuditLogs = (params = {}) => getData(API.get("/admin/audit-logs", { params }));
export const getAdminSettings = () => getData(API.get("/admin/settings"));
export const saveAdminSetting = (data) => getData(API.put("/admin/settings", data));
