import { getAdminHomepage, replaceCmsImage, validateFeaturedServices } from "../../services/cmsService.js";
import { assertAllowedFields, cleanBoolean, cleanLink, cleanSectionOrder, cleanText } from "../../services/cmsValidation.js";
import { writeAuditLog } from "../../services/auditService.js";

const send = (handler, message) => async (req, res, next) => { try { const homepage = await handler(req); res.json({ success: true, message, data: { homepage } }); } catch (error) { next(error); } };
export const getHomepage = send(() => getAdminHomepage(), "Homepage loaded successfully");
export const updateHero = send(async (req) => {
  assertAllowedFields(req.body, ["heading", "subheading", "primaryButton", "secondaryButton", "isActive"]); const homepage = await getAdminHomepage(); const before = homepage.hero.toObject();
  for (const key of ["heading", "subheading"]) if (req.body[key] !== undefined) homepage.hero[key] = cleanText(req.body[key], key, { max: key === "heading" ? 180 : 500 });
  for (const key of ["primaryButton", "secondaryButton"]) if (req.body[key] !== undefined) { assertAllowedFields(req.body[key], ["text", "link"]); if (req.body[key].text !== undefined) homepage.hero[key].text = cleanText(req.body[key].text, `${key}.text`, { max: 80 }); if (req.body[key].link !== undefined) homepage.hero[key].link = cleanLink(req.body[key].link, `${key}.link`); }
  if (req.body.isActive !== undefined) homepage.hero.isActive = cleanBoolean(req.body.isActive, "isActive"); homepage.status = "draft"; await homepage.save();
  if (req.file) { const oldImage = { ...homepage.hero.image.toObject() }; await replaceCmsImage({ file: req.file, folder: "homepage", oldImage, update: async (image) => { homepage.hero.image = image; return homepage.save(); } }); }
  await writeAuditLog({ req, action: req.file ? "cms.homepage.hero_image_replace" : "cms.homepage.hero_update", entityType: "homepage", entityId: homepage._id, summary: "Updated homepage hero", before, after: homepage.hero }); return homepage;
}, "Homepage hero updated successfully");
export const updateFeaturedServices = send(async (req) => { assertAllowedFields(req.body, ["featuredServiceIds"]); const ids = await validateFeaturedServices(req.body.featuredServiceIds); const homepage = await getAdminHomepage(); const before = homepage.featuredServiceIds; homepage.featuredServiceIds = ids; homepage.status = "draft"; await homepage.save(); await writeAuditLog({ req, action: "cms.homepage.featured_services", entityType: "homepage", entityId: homepage._id, summary: "Changed featured services", before, after: ids }); return homepage; }, "Featured services updated successfully");
export const updateSections = send(async (req) => { assertAllowedFields(req.body, ["sectionVisibility", "sectionOrder"]); const homepage = await getAdminHomepage(); const before = { sectionVisibility: homepage.sectionVisibility, sectionOrder: homepage.sectionOrder }; if (req.body.sectionVisibility) { assertAllowedFields(req.body.sectionVisibility, homepage.sectionOrder); for (const [key, value] of Object.entries(req.body.sectionVisibility)) homepage.sectionVisibility[key] = cleanBoolean(value, key); } if (req.body.sectionOrder) homepage.sectionOrder = cleanSectionOrder(req.body.sectionOrder); homepage.status = "draft"; await homepage.save(); await writeAuditLog({ req, action: "cms.homepage.sections", entityType: "homepage", entityId: homepage._id, summary: "Changed homepage section visibility or order", before, after: { sectionVisibility: homepage.sectionVisibility, sectionOrder: homepage.sectionOrder } }); return homepage; }, "Homepage sections updated successfully");
export const publishHomepage = send(async (req) => { assertAllowedFields(req.body || {}, []); const homepage = await getAdminHomepage(); homepage.status = "published"; homepage.publishedAt = new Date(); homepage.publishedSnapshot = { hero: homepage.hero.toObject(), featuredServiceIds: homepage.featuredServiceIds.map(String), sectionVisibility: homepage.sectionVisibility.toObject(), sectionOrder: [...homepage.sectionOrder] }; await homepage.save(); await writeAuditLog({ req, action: "cms.homepage.publish", entityType: "homepage", entityId: homepage._id, summary: "Published homepage", after: { status: homepage.status, publishedAt: homepage.publishedAt } }); return homepage; }, "Homepage published successfully");
