import { getAdminSettings, replaceCmsImage } from "../../services/cmsService.js";
import { assertAllowedFields, cleanEmail, cleanLink, cleanPhone, cleanText } from "../../services/cmsValidation.js";
import { writeAuditLog } from "../../services/auditService.js";
import { ApiError } from "../../utils/ApiError.js";
const send = (handler, message) => async (req, res, next) => { try { const settings = await handler(req); res.json({ success: true, message, data: { settings } }); } catch (error) { next(error); } };
export const getSiteSettings = send(() => getAdminSettings(), "Site settings loaded successfully");
export const updateSiteSettings = send(async (req) => { assertAllowedFields(req.body, ["siteName", "shortSiteName", "tagline", "logo", "general", "contact", "socialLinks", "footer", "footerSections", "legal", "seo"]); const settings = await getAdminSettings(); const before = settings.toObject();
  if (req.body.siteName !== undefined) settings.siteName = cleanText(req.body.siteName, "siteName", { required: true, max: 120 });
  if (req.body.shortSiteName !== undefined) settings.shortSiteName = cleanText(req.body.shortSiteName, "shortSiteName", { required: true, max: 60 });
  if (req.body.tagline !== undefined) settings.tagline = cleanText(req.body.tagline, "tagline", { max: 240 });
  if (req.body.logo?.altText !== undefined) settings.logo.altText = cleanText(req.body.logo.altText, "logo.altText", { max: 160 });
  if (req.body.general) { assertAllowedFields(req.body.general, ["defaultCurrency", "defaultLanguage", "maintenanceMode", "registrationAvailable", "defaultPaginationSize", "announcementBar"]); for (const key of ["defaultCurrency", "defaultLanguage", "announcementBar"]) if (req.body.general[key] !== undefined) settings.general[key] = cleanText(req.body.general[key], key, { max: key === "announcementBar" ? 300 : 30 }); for (const key of ["maintenanceMode", "registrationAvailable"]) if (req.body.general[key] !== undefined) settings.general[key] = ["true", true].includes(req.body.general[key]); if (req.body.general.defaultPaginationSize !== undefined) { const size = Number(req.body.general.defaultPaginationSize); if (!Number.isInteger(size) || size < 5 || size > 100) throw new ApiError(400, "defaultPaginationSize must be between 5 and 100"); settings.general.defaultPaginationSize = size; } }
  if (req.body.contact) { assertAllowedFields(req.body.contact, ["phone", "alternatePhone", "email", "salesEmail", "supportEmail", "whatsapp", "address", "city", "state", "pincode", "workingHours", "mapUrl", "supportText"]); for (const [key, value] of Object.entries(req.body.contact)) { if (["email", "salesEmail", "supportEmail"].includes(key)) settings.contact[key] = cleanEmail(value, key); else if (["phone", "alternatePhone", "whatsapp"].includes(key)) settings.contact[key] = cleanPhone(value, key); else if (key === "mapUrl") settings.contact[key] = cleanLink(value, key, { relative: false }); else { const text = cleanText(value, key, { max: ["address", "supportText"].includes(key) ? 500 : 160 }); if (key === "pincode" && text && !/^\d{6}$/.test(text)) throw new ApiError(400, "pincode must contain 6 digits"); settings.contact[key] = text; } } }
  if (req.body.socialLinks) { assertAllowedFields(req.body.socialLinks, ["facebook", "instagram", "youtube", "linkedin", "twitter"]); for (const [key, value] of Object.entries(req.body.socialLinks)) settings.socialLinks[key] = cleanLink(value, key, { relative: false }); }
  if (req.body.footer) { assertAllowedFields(req.body.footer, ["shortDescription", "copyrightText", "supportText"]); for (const [key, value] of Object.entries(req.body.footer)) settings.footer[key] = cleanText(value, key, { max: 500 }); }
  if (req.body.footerSections) { if (!Array.isArray(req.body.footerSections) || req.body.footerSections.length > 10) throw new ApiError(400, "footerSections must be an array of at most 10 sections"); settings.footerSections = req.body.footerSections.map((section) => { assertAllowedFields(section, ["title", "isActive", "displayOrder", "links"]); if (!Array.isArray(section.links) || section.links.length > 20) throw new ApiError(400, "Each footer section can contain at most 20 links"); return { title: cleanText(section.title, "footer section title", { required: true, max: 100 }), isActive: section.isActive !== false, displayOrder: Number(section.displayOrder || 0), links: section.links.map((link) => { assertAllowedFields(link, ["label", "url", "isExternal", "isActive", "displayOrder"]); return { label: cleanText(link.label, "footer link label", { required: true, max: 100 }), url: cleanLink(link.url, "footer link URL"), isExternal: Boolean(link.isExternal), isActive: link.isActive !== false, displayOrder: Number(link.displayOrder || 0) }; }) }; }); }
  if (req.body.legal) { assertAllowedFields(req.body.legal, ["serviceDisclaimer", "refundDisclaimer"]); for (const [key, value] of Object.entries(req.body.legal)) settings.legal[key] = cleanText(value, key, { max: 1200 }); }
  if (req.body.seo) { assertAllowedFields(req.body.seo, ["defaultTitle", "titleTemplate", "defaultDescription", "defaultKeywords", "siteUrl", "twitterCardType"]); for (const key of ["defaultTitle", "titleTemplate", "defaultDescription"]) if (req.body.seo[key] !== undefined) settings.seo[key] = cleanText(req.body.seo[key], key, { max: key === "defaultDescription" ? 500 : 180 }); if (req.body.seo.siteUrl !== undefined) settings.seo.siteUrl = cleanLink(req.body.seo.siteUrl, "siteUrl", { relative: false }); if (req.body.seo.twitterCardType !== undefined) { if (!["summary", "summary_large_image"].includes(req.body.seo.twitterCardType)) throw new ApiError(400, "Invalid Twitter card type"); settings.seo.twitterCardType = req.body.seo.twitterCardType; } if (req.body.seo.defaultKeywords !== undefined) { if (!Array.isArray(req.body.seo.defaultKeywords) || req.body.seo.defaultKeywords.length > 30) throw new ApiError(400, "defaultKeywords must be an array of at most 30 items"); settings.seo.defaultKeywords = req.body.seo.defaultKeywords.map((value) => cleanText(value, "keyword", { max: 60 })); } }
  await settings.save(); await writeAuditLog({ req, action: "cms.site_settings.update", entityType: "site_settings", entityId: settings._id, summary: "Updated public site settings", before, after: settings }); return settings;
}, "Site settings updated successfully");
const replace = (field, folder) => send(async (req) => { const settings = await getAdminSettings(); const oldImage = settings[field === "logo" ? "logo" : "seo"].defaultImage || settings.logo; const result = await replaceCmsImage({ file: req.file, folder, oldImage, update: async (image) => { if (field === "logo") settings.logo = { ...settings.logo.toObject(), ...image }; else settings.seo.defaultImage = image; return settings.save(); } }); await writeAuditLog({ req, action: `cms.site_settings.${field}_replace`, entityType: "site_settings", entityId: settings._id, summary: `Replaced site ${field}` }); return result; }, `Site ${field} updated successfully`);
export const updateLogo = replace("logo", "site-logo"); export const updateSeoImage = replace("seo_image", "seo");
