import { getAdminSettings, replaceCmsImage } from "../../services/cmsService.js";
import { assertAllowedFields, cleanEmail, cleanLink, cleanPhone, cleanText } from "../../services/cmsValidation.js";
import { writeAuditLog } from "../../services/auditService.js";
import { ApiError } from "../../utils/ApiError.js";
const send = (handler, message) => async (req, res, next) => { try { const settings = await handler(req); res.json({ success: true, message, data: { settings } }); } catch (error) { next(error); } };
export const getSiteSettings = send(() => getAdminSettings(), "Site settings loaded successfully");
export const updateSiteSettings = send(async (req) => { assertAllowedFields(req.body, ["siteName", "logo", "contact", "socialLinks", "footer", "legal", "seo"]); const settings = await getAdminSettings(); const before = settings.toObject();
  if (req.body.siteName !== undefined) settings.siteName = cleanText(req.body.siteName, "siteName", { required: true, max: 120 });
  if (req.body.logo?.altText !== undefined) settings.logo.altText = cleanText(req.body.logo.altText, "logo.altText", { max: 160 });
  if (req.body.contact) { assertAllowedFields(req.body.contact, ["phone", "alternatePhone", "email", "supportEmail", "whatsapp", "address", "city", "state", "pincode", "workingHours"]); for (const [key, value] of Object.entries(req.body.contact)) { if (["email", "supportEmail"].includes(key)) settings.contact[key] = cleanEmail(value, key); else if (["phone", "alternatePhone", "whatsapp"].includes(key)) settings.contact[key] = cleanPhone(value, key); else { const text = cleanText(value, key, { max: key === "address" ? 500 : 160 }); if (key === "pincode" && text && !/^\d{6}$/.test(text)) throw new ApiError(400, "pincode must contain 6 digits"); settings.contact[key] = text; } } }
  if (req.body.socialLinks) { assertAllowedFields(req.body.socialLinks, ["facebook", "instagram", "youtube", "linkedin", "twitter"]); for (const [key, value] of Object.entries(req.body.socialLinks)) settings.socialLinks[key] = cleanLink(value, key, { relative: false }); }
  if (req.body.footer) { assertAllowedFields(req.body.footer, ["shortDescription", "copyrightText", "supportText"]); for (const [key, value] of Object.entries(req.body.footer)) settings.footer[key] = cleanText(value, key, { max: 500 }); }
  if (req.body.legal) { assertAllowedFields(req.body.legal, ["serviceDisclaimer", "refundDisclaimer"]); for (const [key, value] of Object.entries(req.body.legal)) settings.legal[key] = cleanText(value, key, { max: 1200 }); }
  if (req.body.seo) { assertAllowedFields(req.body.seo, ["defaultTitle", "defaultDescription", "defaultKeywords"]); for (const key of ["defaultTitle", "defaultDescription"]) if (req.body.seo[key] !== undefined) settings.seo[key] = cleanText(req.body.seo[key], key, { max: key === "defaultTitle" ? 180 : 500 }); if (req.body.seo.defaultKeywords !== undefined) { if (!Array.isArray(req.body.seo.defaultKeywords) || req.body.seo.defaultKeywords.length > 30) throw new ApiError(400, "defaultKeywords must be an array of at most 30 items"); settings.seo.defaultKeywords = req.body.seo.defaultKeywords.map((value) => cleanText(value, "keyword", { max: 60 })); } }
  await settings.save(); await writeAuditLog({ req, action: "cms.site_settings.update", entityType: "site_settings", entityId: settings._id, summary: "Updated public site settings", before, after: settings }); return settings;
}, "Site settings updated successfully");
const replace = (field, folder) => send(async (req) => { const settings = await getAdminSettings(); const oldImage = settings[field === "logo" ? "logo" : "seo"].defaultImage || settings.logo; const result = await replaceCmsImage({ file: req.file, folder, oldImage, update: async (image) => { if (field === "logo") settings.logo = { ...settings.logo.toObject(), ...image }; else settings.seo.defaultImage = image; return settings.save(); } }); await writeAuditLog({ req, action: `cms.site_settings.${field}_replace`, entityType: "site_settings", entityId: settings._id, summary: `Replaced site ${field}` }); return result; }, `Site ${field} updated successfully`);
export const updateLogo = replace("logo", "site-logo"); export const updateSeoImage = replace("seo_image", "seo");
