import { useEffect, useState } from "react";
import { getPartnerProfile, updatePartnerProfile } from "../../api/partnerApi";
import EmptyState from "../../components/dashboard/EmptyState";
import LoadingSkeleton from "../../components/dashboard/LoadingSkeleton";

const PartnerProfile = () => {
  const [profile, setProfile] = useState(null); const [error, setError] = useState(""); const [feedback, setFeedback] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { getPartnerProfile().then((response) => setProfile(response.profile)).catch((requestError) => setError(requestError.response?.data?.message || "Partner profile not found.")); }, []);
  const save = async (event) => { event.preventDefault(); setSaving(true); setFeedback(""); try { const payload = Object.fromEntries(["businessName", "ownerName", "mobile", "email", "city", "state", "pincode", "gstNumber", "businessType", "availability"].map((key) => [key, profile[key]])); payload.serviceCategories = profile.serviceCategories; payload.serviceAreas = profile.serviceAreas; const response = await updatePartnerProfile(payload); setProfile((current) => ({ ...current, ...response.profile })); setFeedback("Profile updated."); } catch (requestError) { setFeedback(requestError.response?.data?.message || "Unable to update profile."); } finally { setSaving(false); } };
  if (error) return <EmptyState title="Profile unavailable" description={error} />; if (!profile) return <LoadingSkeleton count={6} />;
  return <form onSubmit={save} className="space-y-6"><div><h2 className="text-2xl font-bold">Partner profile</h2><p className="mt-1 text-slate-500">Verification can only be changed by Karlo administration.</p></div>{feedback && <p className="rounded-xl bg-blue-50 p-4 text-sm text-blue-900">{feedback}</p>}<section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex justify-between gap-4"><div><h3 className="text-xl font-bold">{profile.businessName}</h3><p className="text-sm text-slate-500">{profile.userId}</p></div><span className="h-fit rounded-full bg-blue-50 px-3 py-1 text-sm font-semibold text-blue-700">{profile.verificationStatus}</span></div><div className="mt-6 grid gap-4 md:grid-cols-2">{[["businessName", "Business name"], ["ownerName", "Owner name"], ["mobile", "Mobile"], ["email", "Email"], ["city", "City"], ["state", "State"], ["pincode", "Pincode"], ["gstNumber", "GST number"], ["businessType", "Business type"]].map(([key, label]) => <label key={key} className="text-sm font-semibold">{label}<input required={!['email','gstNumber'].includes(key)} value={profile[key] || ""} onChange={(event) => setProfile({ ...profile, [key]: event.target.value })} className="mt-1 w-full rounded-xl border px-3 py-2.5" /></label>)}<label className="text-sm font-semibold">Service categories (comma-separated)<input value={(profile.serviceCategories || []).join(", ")} onChange={(event) => setProfile({ ...profile, serviceCategories: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} className="mt-1 w-full rounded-xl border px-3 py-2.5" /></label><label className="text-sm font-semibold">Service cities (comma-separated)<input value={(profile.serviceAreas || []).join(", ")} onChange={(event) => setProfile({ ...profile, serviceAreas: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} className="mt-1 w-full rounded-xl border px-3 py-2.5" /></label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={profile.availability} onChange={(event) => setProfile({ ...profile, availability: event.target.checked })} /> Available for new leads</label></div><button disabled={saving} className="mt-6 rounded-xl bg-blue-700 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{saving ? "Saving..." : "Save profile"}</button></section></form>;
};
export default PartnerProfile;
