import { ArrowLeft, Upload } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { addPartnerRemark, getPartnerApplication, requestPartnerDocuments, updatePartnerApplicationStatus, uploadCompletionDocuments } from "../../api/partnerApi";
import EmptyState from "../../components/dashboard/EmptyState";
import LoadingSkeleton from "../../components/dashboard/LoadingSkeleton";
import StatusBadge from "../../components/dashboard/StatusBadge";
import DocumentViewer from "../../components/documents/DocumentViewer";
import { formatDate, formatFieldName, formatFieldValue } from "../../utils/dashboardFormatters";

const statuses = ["Documents Required", "Processing", "Approved", "Completed", "Rejected"];
const PartnerApplicationDetails = () => {
  const { id } = useParams(); const [application, setApplication] = useState(null); const [error, setError] = useState(""); const [feedback, setFeedback] = useState(""); const [busy, setBusy] = useState(false); const [refresh, setRefresh] = useState(0);
  const [status, setStatus] = useState("Processing"); const [statusRemarks, setStatusRemarks] = useState(""); const [remark, setRemark] = useState(""); const [documentRequest, setDocumentRequest] = useState(""); const [completionFiles, setCompletionFiles] = useState([]);
  useEffect(() => { let active = true; getPartnerApplication(id).then((response) => active && setApplication(response.application)).catch((requestError) => active && setError(requestError.response?.data?.message || "Application not found.")); return () => { active = false; }; }, [id, refresh]);
  const run = async (action, message) => { setBusy(true); setFeedback(""); try { await action(); setFeedback(message); setRefresh((value) => value + 1); } catch (requestError) { setFeedback(requestError.response?.data?.message || "Action failed."); } finally { setBusy(false); } };
  if (error) return <EmptyState title="Application unavailable" description={error} action={<Link to="/partner/accepted-leads" className="font-semibold text-blue-700">Back to accepted leads</Link>} />;
  if (!application) return <LoadingSkeleton count={6} />;
  const labels = Object.fromEntries((application.serviceForm?.fields || []).map((field) => [field.name, field.label]));
  return <div className="space-y-6"><Link to="/partner/accepted-leads" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-700"><ArrowLeft size={17} /> Back to accepted leads</Link>{feedback && <p className="rounded-xl bg-blue-50 p-4 text-sm text-blue-900">{feedback}</p>}<section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex justify-between gap-4"><div><p className="font-semibold text-blue-700">{application.applicationNumber}</p><h2 className="mt-2 text-2xl font-bold">{application.service?.title}</h2><p className="mt-2 text-slate-500">Customer: {application.customerName} · Accepted {formatDate(application.assignedAt)}</p></div><StatusBadge status={application.status} /></div></section>
    <section className="grid gap-5 xl:grid-cols-3"><div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Update progress</h3><select value={status} onChange={(event) => setStatus(event.target.value)} className="mt-4 w-full rounded-xl border px-3 py-2.5">{statuses.map((item) => <option key={item}>{item}</option>)}</select><textarea value={statusRemarks} onChange={(event) => setStatusRemarks(event.target.value)} placeholder="Customer-visible note" className="mt-3 w-full rounded-xl border p-3" /><button disabled={busy || status === application.status} onClick={() => run(() => updatePartnerApplicationStatus(id, { status, remarks: statusRemarks }), "Status updated.")} className="mt-3 rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Update status</button></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Customer update</h3><textarea value={remark} onChange={(event) => setRemark(event.target.value)} placeholder="Progress remark" className="mt-4 w-full rounded-xl border p-3" /><button disabled={busy || !remark.trim()} onClick={() => run(() => addPartnerRemark(id, remark), "Remark added.")} className="mt-3 rounded-xl border border-blue-700 px-4 py-2.5 text-sm font-semibold text-blue-700 disabled:opacity-40">Add remark</button></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Request documents</h3><textarea value={documentRequest} onChange={(event) => setDocumentRequest(event.target.value)} placeholder="Describe missing documents" className="mt-4 w-full rounded-xl border p-3" /><button disabled={busy || !documentRequest.trim()} onClick={() => run(() => requestPartnerDocuments(id, documentRequest), "Document request sent.")} className="mt-3 rounded-xl bg-amber-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Request documents</button></div></section>
    <section className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Completion documents</h3><p className="mt-1 text-sm text-slate-500">Upload PDF, JPG or PNG files before marking the work completed.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input type="file" multiple accept=".pdf,image/jpeg,image/png" onChange={(event) => setCompletionFiles([...event.target.files])} className="min-w-0 flex-1 rounded-xl border p-2" /><button disabled={busy || !completionFiles.length} onClick={() => run(() => uploadCompletionDocuments(id, completionFiles), "Completion documents uploaded.")} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40"><Upload size={17} /> Upload</button></div></section>
    <DocumentViewer applicationId={id} title="Assigned application documents" />
    <section className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Required customer information</h3><dl className="mt-5 grid gap-4 sm:grid-cols-2">{Object.entries(application.formData || {}).map(([key, value]) => <div key={key} className="border-b pb-3"><dt className="text-sm text-slate-500">{labels[key] || formatFieldName(key)}</dt><dd className="mt-1 break-words font-semibold">{formatFieldValue(value)}</dd></div>)}</dl></section>
    <section className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Timeline</h3><div className="mt-4 divide-y">{[...application.timeline].reverse().map((item, index) => <div key={`${item.createdAt}-${index}`} className="py-4"><div className="flex justify-between gap-3"><StatusBadge status={item.status} /><span className="text-xs text-slate-400">{formatDate(item.createdAt)}</span></div><p className="mt-2 text-sm text-slate-600">{item.remarks}</p></div>)}</div></section></div>;
};
export default PartnerApplicationDetails;
