import express from "express";
import * as controller from "../controllers/partnerController.js";
import { ROLES } from "../constants/roleConstants.js";
import { developmentAuth, requireRole } from "../middlewares/developmentAuthMiddleware.js";
import { uploadApplicationFiles } from "../middlewares/uploadMiddleware.js";
import { requireLeadMarketplace } from "../middlewares/featureFlagMiddleware.js";
import { requireApprovedPartner } from "../middlewares/partnerApprovalMiddleware.js";

const router = express.Router();
router.use(developmentAuth, requireRole(ROLES.PARTNER));
router.post("/register", controller.register);
router.get("/profile", controller.profile);
router.patch("/profile", controller.updateProfile);
router.use(requireApprovedPartner);
router.get("/dashboard-summary", controller.dashboardSummary);
router.get("/leads", requireLeadMarketplace, controller.listLeads);
router.get("/leads/:id", requireLeadMarketplace, controller.leadDetails);
router.post("/leads/:id/accept", requireLeadMarketplace, controller.acceptLead);
router.get("/accepted-leads", requireLeadMarketplace, controller.acceptedLeads);
router.get("/applications", controller.listApplications);
router.get("/applications/:id", controller.applicationDetails);
router.patch("/applications/:id/status", controller.updateStatus);
router.post("/applications/:id/remarks", controller.addRemark);
router.post("/applications/:id/request-documents", controller.requestDocuments);
router.post("/applications/:id/completion-documents", uploadApplicationFiles, controller.completionDocuments);
export default router;
