const fixed = (governmentFee, serviceCharge, note = "") => ({ governmentFee, serviceCharge, totalAmount: governmentFee + serviceCharge, pricingMode: "fixed", pricingNote: note, requiresAdminReview: false });
const quoted = (pricingMode, pricingNote) => ({ governmentFee: 0, serviceCharge: 0, totalAmount: 0, pricingMode, pricingNote, requiresAdminReview: pricingMode !== "free" });
const time = (displayText, value = null, unit = "depends_on_verification") => ({ value, unit, displayText });
const field = (name, label, type = "text", required = true, order = 0) => ({ name, label, type, required, section: "service", order, ...(type === "file" ? { accept: "image/jpeg,image/png,application/pdf", maxFileSizeMb: 10 } : {}) });
const form = (fields, description = "Provide the information and documents required for this service type.") => ({ title: "Application form", description, sections: [{ id: "service", title: "Service details", description: "Details specific to the selected service type.", order: 10 }], fields });
const variant = (key, title, slug, options = {}) => ({
  key, title, slug, description: options.description || `Apply for ${title.toLowerCase()}.`, keywords: options.keywords || [],
  pricing: options.pricing || quoted("government_portal", "Government or portal fee applies."), processingTime: options.processingTime || time("Depends on authority verification"),
  availabilityStatus: options.availabilityStatus || "available", availabilityMessage: options.availabilityMessage || "", requiredDocuments: options.requiredDocuments || [],
  formConfiguration: options.fields ? form(options.fields) : null, terms: options.terms || [], displayOrder: options.displayOrder || 0, isActive: options.isActive !== false,
});
const parent = (title, slug, category, variants, options = {}) => ({
  title, slug, category, variants, description: options.description || `Choose the ${title.toLowerCase()} option that matches your requirement.`, icon: options.icon || "Document",
  dashboardCategory: options.dashboardCategory || "other-services", isPopular: Boolean(options.isPopular), isFeatured: Boolean(options.isFeatured), isActive: true, displayOrder: options.displayOrder || 0,
  availabilityStatus: "available", pricing: quoted("contact_support", "Choose a service type to see pricing."), estimatedProcessingTime: time("Variable by service type"),
  migrationStatus: "parent", migrationSource: options.migrationSource || "service-catalog-v2", legacySlugs: options.legacySlugs || [], keywords: options.keywords || [], fulfillmentType: options.fulfillmentType || "internal", variantSelectionLabel: options.variantSelectionLabel || "Choose Service Type",
});
const docs = {
  pan: ["Aadhaar Card", "Live Photo", "Signature"], passport: ["Aadhaar Card", "PAN Card", "10th Marksheet"],
};
const panFields = [field("fatherName", "Father Name", "text", true, 10), field("aadhaarCard", "Aadhaar Card", "file", true, 20), field("livePhoto", "Live Photo", "file", true, 30), field("signature", "Signature", "file", true, 40)];
const passportFields = [field("motherName", "Mother Name", "text", true, 10), field("aadhaarCard", "Aadhaar Card", "file", true, 20), field("panCard", "PAN Card", "file", true, 30), field("tenthMarksheet", "10th Marksheet", "file", true, 40)];
const addressProofOptions = ["Electricity Bill", "Rent Agreement", "Voter ID Card", "Bank Passbook"].map((label) => ({ label, value: label.toLowerCase().replaceAll(" ", "-") }));
const certificateFields = ({ includeFamilyCasteCertificate = false } = {}) => [
  field("fatherName", "Father Name", "text", true, 10), field("motherName", "Mother Name", "text", true, 20),
  field("livePhoto", "Live Photo", "file", true, 30), field("aadhaarCard", "Aadhaar Card", "file", true, 40),
  { ...field("addressProof", "Address Proof - Any One", "file", true, 50), documentOptions: addressProofOptions, helpText: "Select and upload any one accepted address proof." },
  field("selfDeclarationOrSignature", "Self Declaration or Signature", "file", true, 60),
  ...(includeFamilyCasteCertificate ? [field("familyCasteCertificate", "Family Member's Caste Certificate", "file", true, 70)] : []),
];
const certificateDocuments = ["Live Photo", "Aadhaar Card", "Address Proof - Any One", "Self Declaration or Signature"];
const certificatePricing = () => ({ governmentFee: 0, serviceCharge: 80, totalAmount: 80, pricingMode: "variable", pricingNote: "Government fee may vary by state.", requiresAdminReview: true });

export const parentServiceSeedData = [
  parent("PAN Card", "pan-card", "Identity", [
    variant("new", "New PAN Card", "new-pan-card", { pricing: fixed(107, 50), processingTime: time("3-4 days", 4, "days"), requiredDocuments: docs.pan, fields: panFields, keywords: ["new pan"] }),
    variant("correction", "PAN Card Correction", "pan-correction", { pricing: fixed(107, 100), processingTime: time("3-10 days", 10, "days"), requiredDocuments: [...docs.pan, "Correction Proof"], fields: [field("correctionType", "Correction Type", "text", true, 5), ...panFields, field("correctionProof", "Correction Proof", "file", true, 50)], keywords: ["change", "correction"] }),
    variant("lost", "Lost PAN Card", "lost-pan-card", { requiredDocuments: docs.pan, fields: panFields, keywords: ["duplicate pan"] }),
    variant("pvc", "PAN PVC Order", "pan-pvc-order", { requiredDocuments: ["PAN or acknowledgement details"], fields: [field("panNumber", "PAN Number")], keywords: ["plastic pan"] }),
    variant("aadhaar-linking", "PAN-Aadhaar Linking", "pan-aadhaar-linking", { requiredDocuments: ["PAN Card", "Aadhaar Card"], fields: [field("panNumber", "PAN Number"), field("aadhaarNumber", "Aadhaar Number")], keywords: ["link pan aadhaar"] }),
  ], { icon: "IdCard", dashboardCategory: "government-id", isPopular: true, isFeatured: true, legacySlugs: ["pan-correction", "pan-card-correction"], keywords: ["correction", "lost", "pvc"] }),
  parent("Passport", "passport", "Identity", [
    variant("normal", "Normal Passport", "normal-passport", { pricing: fixed(1500, 200), processingTime: time("15-30 days", 30, "days"), requiredDocuments: docs.passport, fields: passportFields }),
    variant("tatkal", "Tatkal Passport", "tatkal-passport", { pricing: fixed(3500, 300), processingTime: time("1-3 days", 3, "days"), requiredDocuments: docs.passport, fields: passportFields }),
    variant("renewal", "Passport Renewal", "passport-renewal", { pricing: fixed(1500, 250), processingTime: time("7-15 days", 15, "days"), requiredDocuments: [...docs.passport, "Old Passport or FIR"], fields: [...passportFields, field("oldPassportOrFir", "Old Passport or FIR", "file", true, 50)] }),
  ], { icon: "Plane", dashboardCategory: "government-id", isPopular: true, legacySlugs: ["passport-service"], keywords: ["normal", "tatkal", "renewal"] }),
  parent("Insurance", "insurance", "Insurance", [variant("first-party", "First-Party Insurance", "first-party-insurance", { pricing: quoted("variable", "Premium depends on the vehicle, coverage and insurer quotation."), processingTime: time("Contact support", null, "contact_support") }), variant("third-party", "Third-Party Insurance", "third-party-insurance", { pricing: quoted("variable", "Premium depends on the vehicle and insurer quotation."), processingTime: time("Contact support", null, "contact_support") }), variant("renewal", "Insurance Renewal", "insurance-renewal", { pricing: quoted("variable", "Renewal premium depends on the policy and insurer quotation."), processingTime: time("Contact support", null, "contact_support") })], { icon: "Shield", keywords: ["renewal", "first party", "third party"] }),
  parent("Police e-Help", "police-e-help", "Police", [variant("verification", "Police Verification", "police-verification"), variant("fir", "FIR", "fir", { keywords: ["first information report"] }), variant("lost-report", "Lost Report", "lost-report")], { icon: "BadgeCheck", keywords: ["fir", "verification", "lost report"] }),
  parent("eDistrict Services", "edistrict-services", "certificates", [
    variant("income-certificate", "Income Certificate", "income-certificate", { description: "Apply for an Income Certificate with configurable state-specific document support.", pricing: certificatePricing(), processingTime: time("7-20 days", 20, "days"), requiredDocuments: certificateDocuments, fields: certificateFields(), displayOrder: 0, keywords: ["income certificate"] }),
    variant("domicile-certificate", "Domicile Certificate", "domicile-certificate", { description: "Apply for a Domicile Certificate using the documents configured for your service area.", pricing: certificatePricing(), processingTime: time("7-20 days", 20, "days"), requiredDocuments: certificateDocuments, fields: certificateFields(), displayOrder: 1, keywords: ["domicile", "residence certificate"] }),
    variant("caste-certificate", "Caste Certificate", "caste-certificate", { description: "Apply for a Caste Certificate with the additional family caste certificate requirement.", pricing: certificatePricing(), processingTime: time("7-20 days", 20, "days"), requiredDocuments: [...certificateDocuments, "Family Member's Caste Certificate"], fields: certificateFields({ includeFamilyCasteCertificate: true }), displayOrder: 2, keywords: ["caste certificate"] }),
  ], { description: "Karlo Digital Services helps customers apply for Income, Domicile and Caste Certificates through a simple online process.", icon: "FileBadge", dashboardCategory: "online-forms", legacySlugs: ["certificates"], keywords: ["income certificate", "domicile", "caste"], variantSelectionLabel: "Choose Certificate Type", migrationSource: "service-catalog-v3-edistrict" }),
  parent("EPFO", "epfo", "Financial", [variant("withdrawal", "PF Withdrawal", "pf-withdrawal", { pricing: quoted("contact_support", "Contact support for eligibility and final service charge.") }), variant("kyc", "PF KYC", "pf-kyc"), variant("nomination", "PF Nomination", "pf-nomination"), variant("member-transfer", "Member ID Transfer / Activation", "pf-member-transfer")], { icon: "Wallet", keywords: ["pf", "kyc", "nomination", "uan"] }),
  parent("Aadhaar Services", "aadhaar-services", "Identity", [variant("address-change", "Aadhaar Address Change", "aadhaar-address-update"), variant("lost", "Lost Aadhaar", "lost-aadhaar-card")], { icon: "Fingerprint", dashboardCategory: "government-id", keywords: ["uidai", "address", "lost aadhaar"] }),
  parent("Driving Licence", "driving-licence", "Transport", [variant("new", "New Driving Licence", "new-driving-licence"), variant("renewal", "Driving Licence Renewal", "driving-licence-renewal"), variant("duplicate", "Duplicate Copy", "driving-licence-duplicate-copy"), variant("lost", "Lost Licence", "lost-driving-licence")], { icon: "Car", dashboardCategory: "government-id", keywords: ["renewal", "duplicate", "lost licence"] }),
  parent("Railway Ticket", "railway-ticket", "Travel", [variant("second-sitting", "Second Sitting", "railway-second-sitting", { pricing: quoted("government_portal", "As per IRCTC plus service charge."), processingTime: time("Depends on ticket availability") }), variant("sleeper", "Sleeper", "railway-sleeper", { pricing: quoted("government_portal", "As per IRCTC plus service charge."), processingTime: time("Depends on ticket availability") }), variant("ac", "AC Ticket", "railway-ac", { pricing: quoted("government_portal", "As per IRCTC plus service charge."), processingTime: time("Depends on ticket availability") }), variant("tatkal", "Tatkal", "railway-tatkal", { pricing: quoted("government_portal", "As per IRCTC plus service charge."), availabilityStatus: "temporarily_unavailable", availabilityMessage: "Tatkal booking is currently unavailable.", processingTime: time("Depends on ticket availability") })], { icon: "Train", dashboardCategory: "instant-services", keywords: ["sleeper", "ac", "tatkal", "second sitting"] }),
  parent("Typing Services", "typing-services", "Digital", [variant("hindi", "Hindi Typing", "hindi-typing", { pricing: quoted("variable", "Price depends on page count and formatting."), processingTime: time("Contact support", null, "contact_support") }), variant("english", "English Typing", "english-typing", { pricing: quoted("variable", "Price depends on page count and formatting."), processingTime: time("Contact support", null, "contact_support") })], { icon: "Keyboard", dashboardCategory: "instant-services", keywords: ["hindi", "english"] }),
  parent("Presentation and Design", "presentation-design", "Digital", [variant("powerpoint", "PowerPoint Presentation", "powerpoint-presentation", { pricing: quoted("variable", "Price depends on slide count and design requirements."), processingTime: time("Contact support", null, "contact_support") }), variant("pagemaker", "PageMaker", "pagemaker", { pricing: quoted("variable", "Price depends on page count and design requirements."), processingTime: time("Contact support", null, "contact_support") }), variant("other-design", "Other Design Request", "other-design-request", { pricing: quoted("contact_support", "Contact support with your design brief."), processingTime: time("Contact support", null, "contact_support") })], { icon: "Presentation", keywords: ["powerpoint", "pagemaker", "design"] }),
  parent("Other Forms", "other-forms", "Other", [variant("general", "Generic Other Form Request", "other-form-request", { pricing: quoted("contact_support", "Contact support after sharing the form details."), processingTime: time("Contact support", null, "contact_support"), fields: [field("formName", "Form or Service Name"), field("requestDetails", "Request Details", "textarea")] })], { icon: "FilePlus", keywords: ["other form", "generic request"] }),
];

const standalone = (title, slug, category, dashboardCategory = "other-services") => ({ title, slug, category, dashboardCategory, description: `Get assistance with ${title.toLowerCase()} through Karlo Digital Services.`, icon: "Document", pricing: quoted("contact_support", "Contact support for final pricing."), estimatedProcessingTime: time("Depends on authority verification"), availabilityStatus: "coming_soon", availabilityMessage: "This service will be available after pricing and workflow review.", isActive: true });
export const standaloneServiceSeedData = [
  standalone("ITR Filing", "itr-filing", "Tax"), standalone("GST Registration", "gst-registration", "Business"), standalone("MSME Registration", "msme-registration", "Business", "online-forms"),
  standalone("Voter Card", "voter-card", "Identity", "government-id"), standalone("Voter-Aadhaar Linking", "voter-aadhaar-linking", "Identity", "government-id"), standalone("Divyang Card", "divyang-card", "Identity", "government-id"),
  standalone("E-Shram Card", "e-shram-card", "Labour", "government-id"), standalone("Labour Card", "labour-card", "Labour", "government-id"), standalone("Admission Form", "admission-form", "Education", "education"), standalone("Government Job Form", "government-job-form", "Education", "sarkari-result"),
];
export const serviceCatalogSeedData = [...parentServiceSeedData, ...standaloneServiceSeedData];

export const serviceMigrationGroups = parentServiceSeedData.map((service) => ({ parentSlug: service.slug, variantSlugs: service.variants.map(({ slug }) => slug), legacyParentSlugs: service.legacySlugs || [] }));
