const file = (name, label, options = {}) => ({ name, label, type: "file", required: true, accept: "image/jpeg,image/png,application/pdf", maxFileSizeMb: 10, maxFiles: 1, allowCamera: true, capture: "environment", section: "documents", ...options });
const select = (name, label, values, options = {}) => ({ name, label, type: "select", required: true, options: values.map(([value, optionLabel]) => ({ value, label: optionLabel })), section: "details", ...options });
const text = (name, label, options = {}) => ({ name, label, type: "text", required: false, maxLength: 160, section: "details", ...options });
const addressProof = file("addressProof", "Address Proof — Upload Any One", { documentOptions: [["electricity_bill", "Electricity Bill"], ["rent_agreement", "Rent Agreement"], ["voter_id", "Voter ID Card"], ["bank_passbook", "Bank Passbook"], ["driving_licence", "Driving Licence"]].map(([value, label]) => ({ value, label })) });
const common = { requireEmail: false, allowAdditionalDocuments: true, maxAdditionalDocuments: 6, captchaRequired: true };

export const serviceFormTemplates = [
  { match: /passport/, fields: [select("passportType", "Passport Type", [["fresh", "Fresh"], ["tatkal", "Tatkal"], ["renewal", "Renewal"]]), text("motherName", "Mother Name"), file("aadhaarCard", "Aadhaar Card", { maxFiles: 2 }), file("panCard", "PAN Card"), file("marksheet10", "10th Marksheet"), file("oldPassportOrFir", "Old Passport or FIR", { conditional: { field: "passportType", operator: "equals", value: "renewal" } })] },
  { match: /railway|train-ticket/, fields: [text("fromStation", "From", { required: true }), text("toStation", "To", { required: true }), { name: "journeyDate", label: "Journey Date", type: "date", required: true, section: "details" }, text("trainNumber", "Train Number"), select("ticketCategory", "Ticket Category", [["general", "General"], ["tatkal", "Tatkal"]]), { name: "passengerDetails", label: "Passenger List", type: "textarea", required: true, maxLength: 1500, section: "details" }, file("irctcStatus", "IRCTC Status Screenshot", { required: false })] },
  { match: /msme|udyam/, fields: [file("aadhaarCard", "Aadhaar Card", { maxFiles: 2 }), file("panCard", "PAN Card"), file("officeAddressProof", "Office Address Proof")] },
  { match: /food.*licen/, fields: [file("aadhaarCard", "Aadhaar Card", { maxFiles: 2 }), file("officeAddressProof", "Office Address Proof")] },
  { match: /electricity.*connection/, fields: [file("livePhoto", "Live Photo", { capture: "user" }), file("aadhaarCard", "Aadhaar Card", { maxFiles: 2 }), file("propertyPaper", "Property Paper", { maxFiles: 6 }), file("affidavit", "Affidavit")] },
  { match: /insurance/, fields: [select("insuranceCategory", "Insurance Category", [["first_party", "First Party"], ["third_party", "Third Party"]]), file("rcPhoto", "RC Photo"), file("ownerPan", "Owner PAN Card"), file("oldInsurance", "Old Insurance Copy", { required: false })] },
  { match: /income|domicile|caste/, fields: [select("certificateType", "Certificate Type", [["income", "Income"], ["domicile", "Domicile"], ["caste", "Caste"]]), text("fatherName", "Father Name"), text("motherName", "Mother Name"), file("livePhoto", "Live Photo", { capture: "user" }), file("aadhaarCard", "Aadhaar Card", { maxFiles: 2 }), addressProof, file("selfDeclaration", "Self-declaration or Signature"), file("familyCasteCertificate", "Family Caste Certificate", { required: false, conditional: { field: "certificateType", operator: "equals", value: "caste" } })] },
  { match: /police.*verification/, fields: [file("livePhoto", "Live Photo", { capture: "user" }), file("aadhaarCard", "Aadhaar Card", { maxFiles: 2 })] },
  { match: /fir|lost.*report/, fields: [file("aadhaarCard", "Aadhaar Card", { maxFiles: 2 }), file("signedContent", "Signed Written Content")] },
  { match: /aadhaar.*address/, fields: [addressProof] },
  { match: /ayushman/, fields: [file("livePhoto", "Live Photo", { capture: "user" }), file("aadhaarCard", "Aadhaar Card", { maxFiles: 2 })] },
  { match: /pan/, fields: [select("panServiceType", "PAN Service Type", [["new_pan", "New PAN"], ["correction", "Correction"]]), text("fatherName", "Father Name"), { name: "correctionDetails", label: "Correction Details", type: "textarea", required: true, maxLength: 1000, section: "details", conditional: { field: "panServiceType", operator: "equals", value: "correction" } }, file("aadhaarCard", "Aadhaar Card", { maxFiles: 2 }), file("livePhoto", "Live Photo", { capture: "user" }), file("signature", "Signature"), file("correctionProof", "Correction Proof", { required: true, conditional: { field: "panServiceType", operator: "equals", value: "correction" }, documentOptions: [["marksheet10", "10th Marksheet"], ["voter_id", "Voter ID"], ["driving_licence", "Driving Licence"], ["birth_certificate", "Birth Certificate"]].map(([value, label]) => ({ value, label })) })] },
  { match: /labour.*card/, fields: [file("aadhaarCard", "Aadhaar Card", { maxFiles: 2 }), file("livePhoto", "Live Photo", { capture: "user" }), file("selfDeclaration", "Self-declaration or Signature")] },
  { match: /e-?shram/, fields: [file("aadhaarCard", "Aadhaar Card", { maxFiles: 2 }), file("familyAadhaar", "Family Aadhaar Card", { maxFiles: 6 })] },
  { match: /ration.*card/, fields: [file("livePhoto", "Live Photo", { capture: "user" }), file("aadhaarCard", "Aadhaar Card", { maxFiles: 2 }), file("bankPassbook", "Bank Passbook"), file("familyAadhaar", "Family Aadhaar Card", { maxFiles: 6 })] },
  { match: /other.*form/, fields: [text("formName", "Form Name", { required: true }), text("formCategory", "Category"), file("photo", "Photo", { required: false, capture: "user" }), file("signature", "Signature", { required: false }), file("aadhaarCard", "Aadhaar Card", { required: false, maxFiles: 2 }), file("marksheet10", "10th Marksheet", { required: false })] },
].map((template) => ({ ...common, ...template }));

export const templateForService = (service) => serviceFormTemplates.find(({ match }) => match.test(`${service.slug} ${service.title}`.toLowerCase()));
