/* The load helper intentionally follows the current route id; effects rerun on id changes. */
/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { assignAdminLead, getAdminLead, getAdminPartners, updateAdminLead } from "../../api/adminApi";
import EmptyState from "../../components/dashboard/EmptyState";
import LoadingSkeleton from "../../components/dashboard/LoadingSkeleton";

const AdminLeadDetails = () => { const {id}=useParams(); const [lead,setLead]=useState(null); const [partners,setPartners]=useState([]); const [partner,setPartner]=useState(""); const [feedback,setFeedback]=useState(""); const load=()=>getAdminLead(id).then((r)=>setLead(r.lead)).catch((e)=>setFeedback(e.response?.data?.message||"Unable to load lead.")); useEffect(()=>{load();getAdminPartners({verificationStatus:"approved",limit:100}).then((r)=>setPartners(r.partners));},[id]); const status=async(next)=>{try{const r=await updateAdminLead(id,{status:next});setLead(r.lead);setFeedback(`Lead ${next}.`);}catch(e){setFeedback(e.response?.data?.message||"Unable to update lead.");}}; const assign=async()=>{try{await assignAdminLead(id,partner);setFeedback("Partner assigned with application timeline and notifications updated.");load();}catch(e){setFeedback(e.response?.data?.message||"Unable to assign partner.");}}; if(!lead)return feedback?<EmptyState title="Lead unavailable" description={feedback}/>:<LoadingSkeleton count={5}/>; return <div className="space-y-6"><div><h2 className="text-2xl font-bold">{lead.serviceTitle}</h2><p className="text-slate-500">{lead.applicationNumber} · {lead.city}, {lead.pincode}</p></div>{feedback&&<p className="rounded-xl bg-blue-50 p-3 text-sm text-blue-800">{feedback}</p>}<section className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><strong className="uppercase">{lead.status}</strong><span>₹{lead.leadPrice}</span></div><p className="mt-4 text-sm leading-6 text-slate-600">{lead.safeRequirementSummary}</p><Link to={`/admin/applications/${lead.application?._id||lead.application}`} className="mt-4 inline-block text-sm font-semibold text-blue-700">Open application</Link></section>{["draft","open","accepted"].includes(lead.status)&&<section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Lead actions</h3><div className="mt-4 flex flex-wrap gap-2">{lead.status==="draft"&&<button onClick={()=>status("open")} className="rounded-lg bg-blue-700 px-4 py-2 text-sm text-white">Publish</button>}{lead.status==="open"&&<button onClick={()=>status("expired")} className="rounded-lg border px-4 py-2 text-sm">Expire</button>}<button onClick={()=>status("cancelled")} className="rounded-lg border border-rose-300 px-4 py-2 text-sm text-rose-700">Cancel / withdraw</button></div>{lead.status==="open"&&<div className="mt-5 flex flex-col gap-2 sm:flex-row"><select value={partner} onChange={(e)=>setPartner(e.target.value)} className="min-w-0 flex-1 rounded-lg border px-3 py-2"><option value="">Select approved partner</option>{partners.map((p)=><option key={p._id} value={p.userId}>{p.businessName} — {p.city}</option>)}</select><button disabled={!partner} onClick={assign} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm text-white disabled:opacity-50">Assign manually</button></div>}</section>}</div>; };
export default AdminLeadDetails;
