import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getAdminPartners, updatePartnerVerification } from "../../api/adminApi";
import EmptyState from "../../components/dashboard/EmptyState";
import LoadingSkeleton from "../../components/dashboard/LoadingSkeleton";

const AdminPartners = () => {
  const [partners, setPartners] = useState(null); const [status, setStatus] = useState(""); const [error, setError] = useState(""); const [refresh, setRefresh] = useState(0);
  useEffect(() => { let active = true; getAdminPartners({ verificationStatus: status || undefined, limit: 100 }).then((r) => active && setPartners(r.partners)).catch((e) => active && setError(e.response?.data?.message || "Unable to load partners.")); return () => { active = false; }; }, [status, refresh]);
  const verify = async (item, verificationStatus) => { try { await updatePartnerVerification(item._id, verificationStatus); setRefresh((v) => v + 1); } catch (e) { setError(e.response?.data?.message || "Unable to update partner."); } };
  return <div className="space-y-6"><div><h2 className="text-2xl font-bold">Partners</h2><p className="mt-1 text-slate-500">Verification, service coverage, availability, ratings and lead performance.</p></div><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-xl border px-3 py-2"><option value="">All verification states</option>{["pending","under_review","approved","rejected","suspended"].map((v) => <option key={v}>{v}</option>)}</select>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{!partners ? <LoadingSkeleton count={5} /> : !partners.length ? <EmptyState title="No partners" description="Partner applications will appear here." /> : <div className="grid gap-4 lg:grid-cols-2">{partners.map((item) => <article key={item._id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><Link to={`/admin/partners/${item._id}`} className="font-bold text-blue-700">{item.businessName}</Link><p className="text-xs text-slate-500">{item.city}, {item.state} · {item.userId}</p></div><span className="text-xs font-semibold uppercase">{item.verificationStatus}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><span className="rounded-lg bg-slate-50 p-2">{item.acceptedLeads} accepted</span><span className="rounded-lg bg-slate-50 p-2">{item.completedLeads} completed</span><span className="rounded-lg bg-slate-50 p-2">{item.ratingAverage.toFixed(1)} rating</span></div><select aria-label={`Verification for ${item.businessName}`} value={item.verificationStatus} onChange={(e) => verify(item, e.target.value)} className="mt-4 w-full rounded-lg border px-3 py-2 text-sm">{["pending","under_review","approved","rejected","suspended"].map((v) => <option key={v}>{v}</option>)}</select></article>)}</div>}</div>;
};
export default AdminPartners;
