import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getAdminLeads } from "../../api/adminApi";
import EmptyState from "../../components/dashboard/EmptyState";
import LoadingSkeleton from "../../components/dashboard/LoadingSkeleton";
import { formatDate } from "../../utils/dashboardFormatters";

const AdminLeads = () => { const [data,setData]=useState(null); const [status,setStatus]=useState(""); const [error,setError]=useState(""); useEffect(()=>{let active=true;getAdminLeads({status:status||undefined,limit:100}).then((r)=>active&&setData(r)).catch((e)=>active&&setError(e.response?.data?.message||"Unable to load leads."));return()=>{active=false;};},[status]); return <div className="space-y-6"><div><h2 className="text-2xl font-bold">Lead control</h2><p className="mt-1 text-slate-500">Draft, publish, expire, withdraw and manually route marketplace leads.</p></div><select value={status} onChange={(e)=>setStatus(e.target.value)} className="rounded-xl border px-3 py-2"><option value="">All statuses</option>{["draft","open","accepted","expired","completed","cancelled","rejected"].map((v)=><option key={v}>{v}</option>)}</select>{error&&<EmptyState title="Leads unavailable" description={error}/>} {!data?<LoadingSkeleton count={6}/>:!data.leads.length?<EmptyState title="No leads" description="Publish a partner or hybrid application from its application details."/>:<div className="grid gap-3">{data.leads.map((lead)=><Link key={lead._id} to={`/admin/leads/${lead._id}`} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><strong>{lead.serviceTitle}</strong><span className="text-xs font-semibold uppercase">{lead.status}</span></div><p className="mt-2 text-sm text-slate-600">{lead.applicationNumber} · {lead.city} · ₹{lead.leadPrice}</p><p className="mt-1 text-xs text-slate-400">Expires {formatDate(lead.expiresAt)}</p></Link>)}</div>}</div>; };
export default AdminLeads;
