import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { getAdminPartner, updateAdminPartner } from "../../api/adminApi";
import EmptyState from "../../components/dashboard/EmptyState";
import LoadingSkeleton from "../../components/dashboard/LoadingSkeleton";

const lines = (value) => (value || []).join("\n");
const AdminPartnerDetails = () => { const { id } = useParams(); const [data, setData] = useState(null); const [form, setForm] = useState({}); const [feedback, setFeedback] = useState("");
  useEffect(() => { getAdminPartner(id).then((r) => { setData(r); setForm({ serviceCategories: lines(r.partner.serviceCategories), serviceAreas: lines(r.partner.serviceAreas), availability: r.partner.availability, isActive: r.partner.isActive }); }).catch((e) => setFeedback(e.response?.data?.message || "Unable to load partner.")); }, [id]);
  const save = async (e) => { e.preventDefault(); try { await updateAdminPartner(id, { serviceCategories: form.serviceCategories.split("\n").map((v) => v.trim()).filter(Boolean), serviceAreas: form.serviceAreas.split("\n").map((v) => v.trim()).filter(Boolean), availability: form.availability, isActive: form.isActive }); setFeedback("Partner controls saved."); } catch (err) { setFeedback(err.response?.data?.message || "Unable to save partner."); } };
  if (!data) return feedback ? <EmptyState title="Partner unavailable" description={feedback} /> : <LoadingSkeleton count={6} />; const { partner, performance } = data;
  return <div className="space-y-6"><div><h2 className="text-2xl font-bold">{partner.businessName}</h2><p className="text-slate-500">{partner.ownerName} · {partner.mobile} · {partner.email}</p></div>{feedback && <p className="rounded-xl bg-blue-50 p-3 text-sm text-blue-800">{feedback}</p>}<div className="grid gap-4 sm:grid-cols-4">{[["Accepted",performance.accepted],["Completed",performance.completed],["Acceptance",`${performance.acceptanceRate.toFixed(1)}%`],["Completion",`${performance.completionRate.toFixed(1)}%`]].map(([k,v]) => <div key={k} className="rounded-2xl border bg-white p-4"><strong className="text-xl">{v}</strong><p className="text-xs text-slate-500">{k}</p></div>)}</div><form onSubmit={save} className="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-2"><label className="text-sm font-semibold">Service categories<textarea rows="5" value={form.serviceCategories} onChange={(e) => setForm({...form,serviceCategories:e.target.value})} className="mt-1 w-full rounded-xl border p-3" /></label><label className="text-sm font-semibold">Service areas<textarea rows="5" value={form.serviceAreas} onChange={(e) => setForm({...form,serviceAreas:e.target.value})} className="mt-1 w-full rounded-xl border p-3" /></label><label><input type="checkbox" checked={form.availability} onChange={(e) => setForm({...form,availability:e.target.checked})} /> Available for leads</label><label><input type="checkbox" checked={form.isActive} onChange={(e) => setForm({...form,isActive:e.target.checked})} /> Active account</label><button className="rounded-xl bg-blue-700 px-4 py-2 text-white md:col-span-2">Save controls</button></form><section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Verification documents</h3><div className="mt-3 space-y-2">{partner.verificationDocuments?.length ? partner.verificationDocuments.map((doc, i) => <a key={`${doc.documentType}-${i}`} href={doc.secureUrl} target="_blank" rel="noreferrer" className="block text-sm text-blue-700">{doc.documentType}: {doc.originalName || "View document"}</a>) : <p className="text-sm text-slate-500">No documents uploaded.</p>}</div></section></div>;
};
export default AdminPartnerDetails;
