import { ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { getAdminSettings, saveAdminSetting } from "../../api/adminApi";
import EmptyState from "../../components/dashboard/EmptyState";
import LoadingSkeleton from "../../components/dashboard/LoadingSkeleton";

const AdminSettings = () => {
  const [settings, setSettings] = useState(null); const [form, setForm] = useState({ key: "", value: "", description: "" }); const [feedback, setFeedback] = useState("");
  const load = () => getAdminSettings().then((r) => setSettings(r.settings)).catch((e) => setFeedback(e.response?.data?.message || "Unable to load settings."));
  useEffect(load, []);
  const save = async (event) => { event.preventDefault(); try { await saveAdminSetting(form); setFeedback("Setting saved and audited."); setForm({ key: "", value: "", description: "" }); load(); } catch (e) { setFeedback(e.response?.data?.message || "Unable to save setting."); } };
  return <div className="space-y-6"><div><ShieldCheck className="text-blue-700" size={32} /><h2 className="mt-3 text-2xl font-bold">Platform settings</h2><p className="mt-1 text-slate-500">Non-secret operational configuration. Authentication and credentials remain outside this store.</p></div>{feedback && <p className="rounded-xl bg-blue-50 p-3 text-sm text-blue-800">{feedback}</p>}<form onSubmit={save} className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2"><label className="text-sm font-semibold">Key<input required placeholder="applications.auto_assign" value={form.key} onChange={(e) => setForm({...form,key:e.target.value})} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm font-semibold">Value<input required value={form.value} onChange={(e) => setForm({...form,value:e.target.value})} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm font-semibold md:col-span-2">Description<input value={form.description} onChange={(e) => setForm({...form,description:e.target.value})} className="mt-1 w-full rounded-lg border p-2" /></label><button className="rounded-lg bg-blue-700 px-4 py-2 text-white md:col-span-2">Save setting</button></form>{!settings ? <LoadingSkeleton count={3} /> : !settings.length ? <EmptyState title="No platform settings" description="Defaults remain in effect until a non-secret setting is added." /> : <div className="divide-y rounded-2xl border bg-white">{settings.map((item) => <div key={item._id} className="p-4"><strong>{item.key}</strong><p className="text-sm text-slate-600">{String(item.value)}</p><p className="text-xs text-slate-400">{item.description}</p></div>)}</div>}<p className="text-xs text-slate-500">Development identity: {import.meta.env.VITE_DEV_USER_ID || "dev_admin_001"} ({import.meta.env.VITE_DEV_USER_ROLE || "admin"}). TODO(Clerk): replace route-level development identity with production authentication.</p></div>;
};
export default AdminSettings;
