import { ArrowLeft } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { addApplicationRemark, assignApplication, createApplicationNote, deleteAdminApplication, deleteApplicationNote, getAdminApplicationById, getAdminExperts, getAdminPartners, publishApplicationLead, requestApplicationDocuments, restoreAdminApplication, updateApplicationNote, updateApplicationStatus, updateApplicationWorkflow } from "../../api/adminApi";
import { dashboardFeatures } from "../../config/dashboardFeatures";
import ConfirmDialog from "../../components/dashboard/ConfirmDialog";
import EmptyState from "../../components/dashboard/EmptyState";
import LoadingSkeleton from "../../components/dashboard/LoadingSkeleton";
import StatusBadge from "../../components/dashboard/StatusBadge";
import DocumentViewer from "../../components/documents/DocumentViewer";
import CustomerDocumentsManager from "../../components/documents/CustomerDocumentsManager";
import CrmApplicationActivity from "../../components/crm/CrmApplicationActivity";
import ApplicationWorkflowPanel from "../../components/applications/ApplicationWorkflowPanel";
import { formatDate, formatFieldName, formatFieldValue } from "../../utils/dashboardFormatters";

const statuses = ["Pending", "Submitted", "In Review", "Assigned", "Documents Required", "Waiting For Documents", "Documents Uploaded", "Payment Verified", "Verification Pending", "Verified", "Processing", "Awaiting Admin Review", "Approved", "Completed", "Delivered", "Rejected", "Cancelled", "Archived"];
const defaultLeadExpiry = new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 16);

const AdminApplicationDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [application, setApplication] = useState(null);
  const [experts, setExperts] = useState([]);
  const [partners, setPartners] = useState([]);
  const [error, setError] = useState("");
  const [feedback, setFeedback] = useState({ type: "", message: "" });
  const [refresh, setRefresh] = useState(0);
  const [busy, setBusy] = useState(false);
  const [pending, setPending] = useState(null);
  const [assignment, setAssignment] = useState({ assignmentType: "expert", assignedExpertId: "", assignedPartnerId: "", remarks: "" });
  const [statusData, setStatusData] = useState({ status: "Processing", remarks: "" });
  const [remarkData, setRemarkData] = useState({ visibility: "internal", remarks: "" });
  const [documents, setDocuments] = useState("");
  const [leadData, setLeadData] = useState({ city: "", pincode: "", safeRequirementSummary: "", leadPrice: 0, status: "open", expiresAt: defaultLeadExpiry });
  const [workflowData, setWorkflowData] = useState({ priority: "medium", expectedCompletionAt: "", actualCompletionAt: "", isArchived: false });
  const [note, setNote] = useState("");

  useEffect(() => {
    let active = true;
    Promise.all([getAdminApplicationById(id), getAdminExperts({ status: "active", limit: 100 }), getAdminPartners({ verificationStatus: "approved", limit: 100 })])
      .then(([app, people, partnerData]) => {
        if (!active) return;
        setApplication(app.application);
        setExperts(people.experts);
        setPartners(partnerData.partners);
        setAssignment((current) => ({ ...current, assignmentType: app.application.assignmentType || "none", assignedExpertId: app.application.assignedExpertId || "", assignedPartnerId: app.application.assignedPartnerId || "" }));
        setWorkflowData({ priority: app.application.priority || "medium", expectedCompletionAt: app.application.expectedCompletionAt ? app.application.expectedCompletionAt.slice(0, 16) : "", actualCompletionAt: app.application.actualCompletionAt ? app.application.actualCompletionAt.slice(0, 16) : "", isArchived: Boolean(app.application.isArchived) });
      })
      .catch((requestError) => active && setError(requestError.response?.data?.message || "Unable to load application."));
    return () => { active = false; };
  }, [id, refresh]);

  const run = async (action, success) => {
    setBusy(true); setFeedback({ type: "", message: "" });
    try { await action(); setFeedback({ type: "success", message: success }); setPending(null); setRefresh((value) => value + 1); }
    catch (requestError) { setPending(null); setFeedback({ type: "error", message: requestError.response?.data?.message || "Action failed." }); }
    finally { setBusy(false); }
  };
  const assignmentPayload = () => ({
    assignmentType: assignment.assignmentType,
    assignedExpertId: assignment.assignmentType === "expert" ? assignment.assignedExpertId : undefined,
    assignedPartnerId: assignment.assignmentType === "partner" ? assignment.assignedPartnerId : undefined,
    remarks: assignment.remarks,
  });
  const confirm = () => pending === "assign"
    ? run(() => assignApplication(id, assignmentPayload()), "Assignment updated.")
    : pending === "status"
      ? run(() => updateApplicationStatus(id, statusData), "Status updated.")
      : run(() => requestApplicationDocuments(id, { remarks: documents }), "Document request created.");
  const submitRemark = (event) => { event.preventDefault(); run(() => addApplicationRemark(id, remarkData), `${remarkData.visibility === "internal" ? "Internal" : "Customer-visible"} remark added.`).then(() => setRemarkData({ ...remarkData, remarks: "" })); };
  const saveWorkflow = (event) => { event.preventDefault(); run(() => updateApplicationWorkflow(id, { ...workflowData, expectedCompletionAt: workflowData.expectedCompletionAt || null, actualCompletionAt: workflowData.actualCompletionAt || null }), "Workflow controls updated."); };
  const addNote = (event) => { event.preventDefault(); run(() => createApplicationNote(id, { remarks: note }), "Private note added.").then(() => setNote("")); };
  const editNote = (item) => { const remarks = window.prompt("Edit private note", item.remarks); if (remarks?.trim()) run(() => updateApplicationNote(id, item._id, { remarks }), "Private note updated."); };
  const removeNote = (item) => { if (window.confirm("Delete this private note?")) run(() => deleteApplicationNote(id, item._id), "Private note deleted."); };
  const removeApplication = async () => {
    if (!window.confirm("Soft-delete this application? It will be archived and retained for audit history.")) return;
    setBusy(true);
    try { await deleteAdminApplication(id); navigate("/admin/applications"); }
    catch (requestError) { setFeedback({ type: "error", message: requestError.response?.data?.message || "Unable to delete application." }); setBusy(false); }
  };
  const restoreApplication = () => run(() => restoreAdminApplication(id), "Application restored.");

  if (error) return <EmptyState title="Application unavailable" description={error} />;
  if (!application) return <LoadingSkeleton count={7} />;
  const labels = Object.fromEntries((application.serviceForm?.fields || []).map((field) => [field.name, field.label]));
  const assignmentReady = assignment.assignmentType === "none" || (assignment.assignmentType === "expert" ? assignment.assignedExpertId : assignment.assignedPartnerId.trim());

  return <div className="space-y-6"><Link to="/admin/applications" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-700"><ArrowLeft size={17} /> Back to applications</Link>{feedback.message && <p className={`rounded-xl px-4 py-3 text-sm ${feedback.type === "success" ? "bg-emerald-50 text-emerald-800" : "bg-rose-50 text-rose-800"}`}>{feedback.message}</p>}
    <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="font-semibold text-blue-700">{application.applicationNumber}</p><h2 className="mt-2 text-2xl font-bold">{application.service?.title}</h2><p className="mt-2 text-sm text-slate-500">{application.customerName} · {application.fulfillmentType || "internal"} fulfillment · Submitted {formatDate(application.createdAt)}</p></div><StatusBadge status={application.status} /></div></section>
    <form onSubmit={saveWorkflow} className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm sm:grid-cols-2 xl:grid-cols-6"><label className="text-sm font-semibold">Priority<select value={workflowData.priority} onChange={(event) => setWorkflowData({ ...workflowData, priority: event.target.value })} className="mt-1 w-full rounded-xl border px-3 py-2.5">{["low","medium","high","urgent"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-semibold">Expected completion<input type="datetime-local" value={workflowData.expectedCompletionAt} onChange={(event) => setWorkflowData({ ...workflowData, expectedCompletionAt: event.target.value })} className="mt-1 w-full rounded-xl border px-3 py-2.5" /></label><label className="text-sm font-semibold">Actual completion<input type="datetime-local" value={workflowData.actualCompletionAt} onChange={(event) => setWorkflowData({ ...workflowData, actualCompletionAt: event.target.value })} className="mt-1 w-full rounded-xl border px-3 py-2.5" /></label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={workflowData.isArchived} onChange={(event) => setWorkflowData({ ...workflowData, isArchived: event.target.checked })} /> Archived</label><button disabled={busy || application.isDeleted} className="self-end rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Save workflow</button>{application.isDeleted ? <button type="button" disabled={busy} onClick={restoreApplication} className="self-end rounded-xl border border-emerald-400 px-4 py-2.5 text-sm font-semibold text-emerald-700">Restore application</button> : <button type="button" disabled={busy} onClick={removeApplication} className="self-end rounded-xl border border-rose-300 px-4 py-2.5 text-sm font-semibold text-rose-700">Delete application</button>}</form>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-2xl border bg-white p-4"><p className="text-xs font-bold uppercase text-slate-400">Customer</p><strong className="mt-2 block">{application.applicantName || application.customerName}</strong><p className="text-sm text-slate-500">{application.mobileNumber || "No mobile"} · {application.email || "No email"}</p></article><article className="rounded-2xl border bg-white p-4"><p className="text-xs font-bold uppercase text-slate-400">Partner</p><strong className="mt-2 block">{application.assignedPartner?.businessName || "Unassigned"}</strong><p className="text-sm text-slate-500">{application.assignedPartnerId || "No partner ID"}</p></article><article className="rounded-2xl border bg-white p-4"><p className="text-xs font-bold uppercase text-slate-400">Expert</p><strong className="mt-2 block">{application.assignedExpert?.displayName || "Unassigned"}</strong><p className="text-sm text-slate-500">{application.assignedExpertId || "No expert ID"}</p></article><article className={`rounded-2xl border p-4 ${application.isOverdue ? "border-rose-200 bg-rose-50" : "bg-white"}`}><p className="text-xs font-bold uppercase text-slate-400">Schedule</p><strong className="mt-2 block">Submitted {formatDate(application.submittedAt || application.createdAt)}</strong><p className={application.isOverdue ? "text-sm font-semibold text-rose-700" : "text-sm text-slate-500"}>{application.expectedCompletionAt ? `Due ${formatDate(application.expectedCompletionAt)}` : "No expected completion date"}</p></article></section>
    <section className="grid gap-5 xl:grid-cols-3"><div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Assign work</h3><select value={assignment.assignmentType} onChange={(event) => setAssignment({ ...assignment, assignmentType: event.target.value })} className="mt-4 w-full rounded-xl border px-3 py-2.5"><option value="none">Nobody</option><option value="expert">Expert</option><option value="partner">Partner</option></select>{assignment.assignmentType === "expert" && <select value={assignment.assignedExpertId} onChange={(event) => setAssignment({ ...assignment, assignedExpertId: event.target.value })} className="mt-3 w-full rounded-xl border px-3 py-2.5"><option value="">Select active expert</option>{experts.map((item) => <option key={item._id} value={item.userId}>{item.displayName}</option>)}</select>}{assignment.assignmentType === "partner" && <select value={assignment.assignedPartnerId} onChange={(event) => setAssignment({ ...assignment, assignedPartnerId: event.target.value })} className="mt-3 w-full rounded-xl border px-3 py-2.5"><option value="">Select approved partner</option>{partners.map((item) => <option key={item._id} value={item.userId}>{item.businessName}</option>)}</select>}<textarea value={assignment.remarks} onChange={(event) => setAssignment({ ...assignment, remarks: event.target.value })} placeholder="Assignment remarks" className="mt-3 w-full rounded-xl border px-3 py-2" /><button disabled={!assignmentReady} onClick={() => setPending("assign")} className="mt-3 rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Update assignment</button></div>
      <div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Update status</h3><select value={statusData.status} onChange={(event) => setStatusData({ ...statusData, status: event.target.value })} className="mt-4 w-full rounded-xl border px-3 py-2.5">{statuses.map((item) => <option key={item}>{item}</option>)}</select><textarea value={statusData.remarks} onChange={(event) => setStatusData({ ...statusData, remarks: event.target.value })} placeholder="Customer-facing status remarks" className="mt-3 w-full rounded-xl border px-3 py-2" /><button disabled={statusData.status === application.status} onClick={() => setPending("status")} className="mt-3 rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Update status</button></div>
      <div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Request documents</h3><textarea rows="5" value={documents} onChange={(event) => setDocuments(event.target.value)} placeholder="Describe required documents" className="mt-4 w-full rounded-xl border px-3 py-2" /><button disabled={!documents.trim()} onClick={() => setPending("documents")} className="mt-3 rounded-xl bg-amber-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Request documents</button></div></section>
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Add remark</h3><form onSubmit={submitRemark} className="mt-4 grid gap-3 sm:grid-cols-[180px_minmax(0,1fr)_auto]"><select value={remarkData.visibility} onChange={(event) => setRemarkData({ ...remarkData, visibility: event.target.value })} className="rounded-xl border px-3"><option value="internal">Internal only</option><option value="customer">Customer visible</option></select><textarea required value={remarkData.remarks} onChange={(event) => setRemarkData({ ...remarkData, remarks: event.target.value })} placeholder="Write a remark" className="rounded-xl border px-3 py-2" /><button disabled={busy} className="self-end rounded-xl border border-blue-700 px-4 py-2.5 text-sm font-semibold text-blue-700">Add remark</button></form></section>
    {dashboardFeatures.leadMarketplace && ["partner", "hybrid"].includes(application.fulfillmentType) && !application.assignedExpertId && !application.assignedPartnerId && <section className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Publish to Partner Marketplace</h3><p className="mt-1 text-sm text-slate-500">Use only a privacy-safe summary. Never copy customer names, contact details, IDs or document data here.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><input required value={leadData.city} onChange={(event) => setLeadData({ ...leadData, city: event.target.value })} placeholder="Service city" className="rounded-xl border px-3 py-2.5" /><input required value={leadData.pincode} onChange={(event) => setLeadData({ ...leadData, pincode: event.target.value })} placeholder="Pincode" className="rounded-xl border px-3 py-2.5" /><input required min="0" type="number" value={leadData.leadPrice} onChange={(event) => setLeadData({ ...leadData, leadPrice: Number(event.target.value) })} placeholder="Lead price" className="rounded-xl border px-3 py-2.5" /><textarea required value={leadData.safeRequirementSummary} onChange={(event) => setLeadData({ ...leadData, safeRequirementSummary: event.target.value })} placeholder="Privacy-safe requirement summary" className="rounded-xl border p-3 md:col-span-2" /><input required type="datetime-local" value={leadData.expiresAt} onChange={(event) => setLeadData({ ...leadData, expiresAt: event.target.value })} className="rounded-xl border px-3 py-2.5" /></div><button disabled={busy || !leadData.city || !leadData.pincode || !leadData.safeRequirementSummary.trim()} onClick={() => run(() => publishApplicationLead(id, leadData), "Lead published to the Partner Marketplace.")} className="mt-4 rounded-xl bg-violet-700 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Publish lead</button></section>}
    <section className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Applicant data</h3><dl className="mt-5 grid gap-4 sm:grid-cols-2">{Object.entries(application.formData || {}).map(([key, value]) => <div key={key} className="border-b pb-3"><dt className="text-sm text-slate-500">{labels[key] || formatFieldName(key)}</dt><dd className="mt-1 break-words font-semibold">{formatFieldValue(value)}</dd></div>)}</dl></section>
    <DocumentViewer applicationId={id} title="Application document review" />
    <CustomerDocumentsManager mode="admin" applicationId={id} compact />
    <ApplicationWorkflowPanel applicationId={id} canComment />
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Private admin notes</h3><form onSubmit={addNote} className="mt-3 flex flex-col gap-3 sm:flex-row"><textarea required value={note} onChange={(event) => setNote(event.target.value)} className="min-w-0 flex-1 rounded-xl border p-3" placeholder="Add a private note (never shown to customers)" /><button disabled={busy} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Add note</button></form><div className="mt-4 divide-y">{application.internalRemarks.length ? application.internalRemarks.map((item) => <article key={item._id} className="py-3"><p className="text-sm">{item.remarks}</p><div className="mt-2 flex flex-wrap items-center justify-between gap-2 text-xs text-slate-500"><span>{item.createdBy} · {formatDate(item.updatedAt || item.createdAt)}</span><span className="flex gap-3"><button type="button" onClick={() => editNote(item)} className="font-semibold text-blue-700">Edit</button><button type="button" onClick={() => removeNote(item)} className="font-semibold text-rose-700">Delete</button></span></div></article>) : <p className="text-sm text-slate-500">No private notes.</p>}</div></section>
    {(application.payments?.length > 0 || application.serviceForm) && <section className="grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Payments</h3>{application.payments?.length ? <div className="mt-3 space-y-2">{application.payments.map((payment) => <div key={payment._id} className="flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{payment.paymentId || payment.transactionId || "Payment"}</span><strong>{payment.status} · ₹{payment.amount}</strong></div>)}</div> : <p className="mt-3 text-sm text-slate-500">No payment record.</p>}</article><article className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Declaration and form configuration</h3><p className="mt-3 text-sm">{application.serviceForm?.title || "No declaration form configured"}</p><p className="mt-1 text-xs text-slate-500">{application.serviceForm?.description}</p></article></section>}
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Security and audit activity</h3><div className="mt-4 divide-y">{application.auditActivity?.length ? application.auditActivity.map((item) => <article key={item._id} className="py-3"><div className="flex flex-wrap justify-between gap-2"><strong className="text-sm">{item.summary}</strong><time className="text-xs text-slate-400">{formatDate(item.createdAt)}</time></div><p className="mt-1 text-xs text-slate-500">{item.actorRole} · {item.actorUserId} · {item.action}</p></article>) : <p className="text-sm text-slate-500">No audited actions yet.</p>}</div></section>
    <CrmApplicationActivity applicationId={application._id} />
    <section className="grid gap-6 xl:grid-cols-2"><div className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Customer-visible timeline</h3><div className="mt-4 divide-y">{[...application.timeline].reverse().map((item) => <div key={item._id} className="py-3"><div className="flex justify-between"><StatusBadge status={item.status} /><span className="text-xs text-slate-400">{formatDate(item.createdAt)}</span></div><p className="mt-2 text-sm text-slate-600">{item.remarks}</p></div>)}</div></div><div className="space-y-6"><div className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Internal remarks</h3><div className="mt-3 divide-y">{application.internalRemarks.length ? application.internalRemarks.map((item) => <div key={item._id} className="py-3 text-sm"><p>{item.remarks}</p><p className="mt-1 text-xs text-slate-400">{item.createdBy} · {formatDate(item.createdAt)}</p></div>) : <p className="text-sm text-slate-500">No internal remarks.</p>}</div></div><div className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Assignment history</h3><div className="mt-3 divide-y">{application.assignmentHistory.length ? application.assignmentHistory.map((item) => <div key={item._id} className="py-3 text-sm"><p className="font-semibold">{item.assignmentType || "expert"}: {item.expertUserId || item.partnerUserId}</p><p className="text-slate-500">{item.remarks || "Assigned"}</p><p className="mt-1 text-xs text-slate-400">By {item.assignedBy} · {formatDate(item.createdAt)}{item.isActive ? " · Active" : ""}</p></div>) : <p className="text-sm text-slate-500">No assignment history.</p>}</div></div></div></section>
    <ConfirmDialog open={Boolean(pending)} title={pending === "assign" ? "Confirm assignment" : pending === "status" ? "Confirm status update" : "Confirm document request"} description="This action updates application history and may notify the customer or assignee." confirmLabel="Confirm action" busy={busy} onCancel={() => setPending(null)} onConfirm={confirm} />
  </div>;
};

export default AdminApplicationDetails;
