import { useEffect, useState } from "react";
import { createExpert, getAdminExperts, updateExpert } from "../../api/adminApi";
import EmptyState from "../../components/dashboard/EmptyState";
import LoadingSkeleton from "../../components/dashboard/LoadingSkeleton";

const initialForm = { userId: "", displayName: "", email: "", phone: "", status: "active", categories: "", skills: "", availability: true };
const splitList = (value) => value.split(",").map((item) => item.trim()).filter(Boolean);

const AdminExperts = () => {
  const [experts, setExperts] = useState(null); const [form, setForm] = useState(initialForm); const [feedback, setFeedback] = useState({ type: "", message: "" }); const [refresh, setRefresh] = useState(0);
  useEffect(() => { let active = true; getAdminExperts({ limit: 100 }).then((response) => active && setExperts(response.experts)).catch((error) => active && setFeedback({ type: "error", message: error.response?.data?.message || "Unable to load experts." })); return () => { active = false; }; }, [refresh]);
  const submit = async (event) => { event.preventDefault(); try { await createExpert({ ...form, categories: splitList(form.categories), skills: splitList(form.skills) }); setForm(initialForm); setFeedback({ type: "success", message: "Expert profile created." }); setRefresh((value) => value + 1); } catch (error) { setFeedback({ type: "error", message: error.response?.data?.message || "Unable to create expert." }); } };
  const update = async (expert, changes) => { try { await updateExpert(expert._id, changes); setRefresh((value) => value + 1); } catch (error) { setFeedback({ type: "error", message: error.response?.data?.message || "Unable to update expert." }); } };
  return <div className="space-y-6"><div><h2 className="text-2xl font-bold">Experts</h2><p className="mt-1 text-slate-500">Internal Karlo team members, skills, availability and workload.</p></div>{feedback.message && <p className={`rounded-xl px-4 py-3 text-sm ${feedback.type === "success" ? "bg-emerald-50 text-emerald-800" : "bg-rose-50 text-rose-800"}`}>{feedback.message}</p>}
    <form onSubmit={submit} className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-3"><h3 className="font-bold md:col-span-3">Register development expert</h3>{[["userId","Expert user ID"],["displayName","Display name"],["email","Email"],["phone","Phone"],["categories","Categories (comma separated)"],["skills","Skills (comma separated)"]].map(([name,label]) => <label key={name} className="text-sm font-semibold">{label}<input required={["userId","displayName"].includes(name)} type={name === "email" ? "email" : "text"} value={form[name]} onChange={(event) => setForm({...form,[name]:event.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2.5" /></label>)}<label className="text-sm font-semibold">Status<select value={form.status} onChange={(event) => setForm({...form,status:event.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2.5"><option>active</option><option>inactive</option><option>unavailable</option></select></label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.availability} onChange={(event) => setForm({...form,availability:event.target.checked})} /> Available for assignment</label><button className="rounded-xl bg-blue-700 px-5 py-2.5 text-sm font-semibold text-white">Create expert</button></form>
    {!experts ? <LoadingSkeleton count={4} /> : !experts.length ? <EmptyState title="No experts" description="Register a development expert to enable internal assignments." /> : <div className="grid gap-4 lg:grid-cols-2">{experts.map((item) => <article key={item._id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between gap-4"><div><h3 className="font-bold">{item.displayName}</h3><p className="text-xs text-slate-500">{item.userId}</p></div><select aria-label={`Status for ${item.displayName}`} value={item.status} onChange={(event) => update(item,{status:event.target.value})} className="rounded-lg border px-2 text-sm"><option>active</option><option>inactive</option><option>unavailable</option></select></div><p className="mt-3 text-xs text-slate-500">Categories: {item.categories?.join(", ") || "Any"} · Skills: {item.skills?.join(", ") || "Not set"}</p><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={item.availability ?? true} onChange={(event) => update(item,{availability:event.target.checked})} /> Available</label><div className="mt-5 grid grid-cols-4 gap-2 text-center text-xs"><div className="rounded-lg bg-blue-50 p-2"><strong className="block text-lg">{item.activeAssignments}</strong>Active</div><div className="rounded-lg bg-emerald-50 p-2"><strong className="block text-lg">{item.completedApplications}</strong>Done</div><div className="rounded-lg bg-amber-50 p-2"><strong className="block text-lg">{item.pendingApplications}</strong>Pending</div><div className="rounded-lg bg-violet-50 p-2"><strong className="block text-lg">{item.completionRate.toFixed(0)}%</strong>Rate</div></div></article>)}</div>}
  </div>;
};
export default AdminExperts;
