export const APPLICATION_STATUSES = Object.freeze({
  SUBMITTED: "Submitted",
  ASSIGNED: "Assigned",
  DOCUMENTS_REQUIRED: "Documents Required",
  PROCESSING: "Processing",
  APPROVED: "Approved",
  COMPLETED: "Completed",
  REJECTED: "Rejected",
  CANCELLED: "Cancelled",
});

export const APPLICATION_STATUS_VALUES = Object.freeze(
  Object.values(APPLICATION_STATUSES)
);

export const TERMINAL_APPLICATION_STATUSES = new Set([
  APPLICATION_STATUSES.COMPLETED,
  APPLICATION_STATUSES.REJECTED,
  APPLICATION_STATUSES.CANCELLED,
]);

export const APPLICATION_STATUS_TRANSITIONS = Object.freeze({
  [APPLICATION_STATUSES.SUBMITTED]: [
    APPLICATION_STATUSES.ASSIGNED,
    APPLICATION_STATUSES.DOCUMENTS_REQUIRED,
    APPLICATION_STATUSES.PROCESSING,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.ASSIGNED]: [
    APPLICATION_STATUSES.DOCUMENTS_REQUIRED,
    APPLICATION_STATUSES.PROCESSING,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.DOCUMENTS_REQUIRED]: [
    APPLICATION_STATUSES.PROCESSING,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.PROCESSING]: [
    APPLICATION_STATUSES.DOCUMENTS_REQUIRED,
    APPLICATION_STATUSES.APPROVED,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.APPROVED]: [
    APPLICATION_STATUSES.COMPLETED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.COMPLETED]: [],
  [APPLICATION_STATUSES.REJECTED]: [],
  [APPLICATION_STATUSES.CANCELLED]: [],
});
