export const APPLICATION_STATUSES = Object.freeze({
  PENDING: "Pending",
  SUBMITTED: "Submitted",
  IN_REVIEW: "In Review",
  ASSIGNED: "Assigned",
  DOCUMENTS_REQUIRED: "Documents Required",
  WAITING_FOR_DOCUMENTS: "Waiting For Documents",
  DOCUMENTS_UPLOADED: "Documents Uploaded",
  PAYMENT_VERIFIED: "Payment Verified",
  VERIFICATION_PENDING: "Verification Pending",
  VERIFIED: "Verified",
  PROCESSING: "Processing",
  AWAITING_ADMIN_REVIEW: "Awaiting Admin Review",
  APPROVED: "Approved",
  COMPLETED: "Completed",
  DELIVERED: "Delivered",
  REJECTED: "Rejected",
  CANCELLED: "Cancelled",
  ARCHIVED: "Archived",
});

export const APPLICATION_STATUS_VALUES = Object.freeze(
  Object.values(APPLICATION_STATUSES)
);

export const TERMINAL_APPLICATION_STATUSES = new Set([
  APPLICATION_STATUSES.COMPLETED,
  APPLICATION_STATUSES.DELIVERED,
  APPLICATION_STATUSES.REJECTED,
  APPLICATION_STATUSES.CANCELLED,
  APPLICATION_STATUSES.ARCHIVED,
]);

export const APPLICATION_STATUS_TRANSITIONS = Object.freeze({
  [APPLICATION_STATUSES.PENDING]: [
    APPLICATION_STATUSES.SUBMITTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.SUBMITTED]: [
    APPLICATION_STATUSES.IN_REVIEW,
    APPLICATION_STATUSES.ASSIGNED,
    APPLICATION_STATUSES.DOCUMENTS_REQUIRED,
    APPLICATION_STATUSES.WAITING_FOR_DOCUMENTS,
    APPLICATION_STATUSES.PAYMENT_VERIFIED,
    APPLICATION_STATUSES.PROCESSING,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.IN_REVIEW]: [
    APPLICATION_STATUSES.ASSIGNED,
    APPLICATION_STATUSES.DOCUMENTS_REQUIRED,
    APPLICATION_STATUSES.WAITING_FOR_DOCUMENTS,
    APPLICATION_STATUSES.VERIFICATION_PENDING,
    APPLICATION_STATUSES.PROCESSING,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.ASSIGNED]: [
    APPLICATION_STATUSES.DOCUMENTS_REQUIRED,
    APPLICATION_STATUSES.WAITING_FOR_DOCUMENTS,
    APPLICATION_STATUSES.VERIFICATION_PENDING,
    APPLICATION_STATUSES.PROCESSING,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.DOCUMENTS_REQUIRED]: [
    APPLICATION_STATUSES.DOCUMENTS_UPLOADED,
    APPLICATION_STATUSES.PROCESSING,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.WAITING_FOR_DOCUMENTS]: [
    APPLICATION_STATUSES.DOCUMENTS_UPLOADED,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.DOCUMENTS_UPLOADED]: [
    APPLICATION_STATUSES.VERIFICATION_PENDING,
    APPLICATION_STATUSES.VERIFIED,
    APPLICATION_STATUSES.PROCESSING,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.PAYMENT_VERIFIED]: [
    APPLICATION_STATUSES.ASSIGNED,
    APPLICATION_STATUSES.IN_REVIEW,
    APPLICATION_STATUSES.PROCESSING,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.VERIFICATION_PENDING]: [
    APPLICATION_STATUSES.VERIFIED,
    APPLICATION_STATUSES.DOCUMENTS_REQUIRED,
    APPLICATION_STATUSES.WAITING_FOR_DOCUMENTS,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.VERIFIED]: [
    APPLICATION_STATUSES.PROCESSING,
    APPLICATION_STATUSES.APPROVED,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.PROCESSING]: [
    APPLICATION_STATUSES.DOCUMENTS_REQUIRED,
    APPLICATION_STATUSES.AWAITING_ADMIN_REVIEW,
    APPLICATION_STATUSES.APPROVED,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.AWAITING_ADMIN_REVIEW]: [
    APPLICATION_STATUSES.DOCUMENTS_REQUIRED,
    APPLICATION_STATUSES.PROCESSING,
    APPLICATION_STATUSES.COMPLETED,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.APPROVED]: [
    APPLICATION_STATUSES.COMPLETED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.COMPLETED]: [APPLICATION_STATUSES.DELIVERED],
  [APPLICATION_STATUSES.DELIVERED]: [APPLICATION_STATUSES.ARCHIVED],
  [APPLICATION_STATUSES.REJECTED]: [],
  [APPLICATION_STATUSES.CANCELLED]: [],
  [APPLICATION_STATUSES.ARCHIVED]: [],
});
