import { useEffect, useRef, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import DynamicForm from "../../components/forms/DynamicForm";
import VariantSelector from "../../components/services/VariantSelector";
import { getServiceBySlug, getServiceForm, submitServiceApplication } from "../../api/serviceApi";

const ApplyService = () => {
  const { slug } = useParams(); const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const selectedKey = params.get("type") || "";
  const [service, setService] = useState(null); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [isSubmitting, setIsSubmitting] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState(null); const submissionKey = useRef(crypto.randomUUID());
  useEffect(() => { let active = true; getServiceBySlug(slug, selectedKey).then(async (details) => { if (!active) return; if (details.canonicalUrl) { navigate(details.canonicalUrl.replace(`/services/${details.service.slug}`, `/services/${details.service.slug}/apply`), { replace: true }); return; } setService(details.service); if (details.service.variantCount > 1 && !selectedKey) { setData(null); return; } const key = selectedKey || details.selectedVariantKey; const formData = await getServiceForm(details.service.slug, key); if (active) setData(formData); }).catch((requestError) => active && setError(requestError.response?.data?.message || "Unable to load the application form.")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [slug, selectedKey, navigate]);
  const submit = async (formData) => { try { setIsSubmitting(true); setError(""); setResult(await submitServiceApplication(service.slug, formData, submissionKey.current)); window.scrollTo({ top: 0, behavior: "smooth" }); } catch (requestError) { const response = requestError.response?.data; setError(response?.errors?.join(" ") || response?.message || "Unable to submit your application."); } finally { setIsSubmitting(false); } };
  if (loading) return <p className="mx-auto max-w-3xl px-4 py-16 text-slate-600">Loading application form...</p>;
  if (error && !service) return <div className="mx-auto max-w-3xl px-4 py-16"><p className="rounded-xl bg-red-50 p-5 text-red-700">{error}</p></div>;
  if (result) return <section className="mx-auto max-w-2xl px-4 py-16 sm:px-6"><div className="rounded-3xl border border-emerald-200 bg-white p-8 text-center shadow-sm"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-100 text-3xl text-emerald-700">&#10003;</div><h1 className="mt-6 text-3xl font-bold">Application submitted successfully</h1><p className="mt-6 rounded-xl bg-slate-100 p-4 text-xl font-bold text-blue-700">{result.applicationNumber}</p><p className="mt-4 font-semibold">{result.receipt?.variantTitle || result.receipt?.serviceName}</p><div className="mt-6 flex justify-center"><Link to={`/customer/applications/${result.receipt?.applicationId}`} className="rounded-xl bg-blue-700 px-6 py-3 font-semibold text-white">View Application</Link></div></div></section>;
  if (service?.variantCount > 1 && !selectedKey) return <section className="mx-auto max-w-4xl px-4 py-12 sm:px-6"><Link to={`/services/${service.slug}`} className="font-semibold text-blue-700">Back to service details</Link><div className="mt-6 rounded-3xl border bg-white p-6 shadow-sm sm:p-8"><h1 className="mb-6 text-3xl font-bold">Apply for {service.title}</h1><VariantSelector variants={service.variants} selectedKey="" onSelect={(type) => setParams({ type })} legend={service.variantSelectionLabel} /></div></section>;
  if (!data) return <div className="mx-auto max-w-3xl px-4 py-16"><p className="rounded-xl bg-red-50 p-5 text-red-700">{error || "Application form is unavailable."}</p></div>;
  return <section className="mx-auto max-w-3xl px-4 py-10 sm:px-6 sm:py-14"><Link to={`/services/${service.slug}${data.variant ? `?type=${data.variant.key}` : ""}`} className="font-semibold text-blue-700">Back to service details</Link><header className="mb-7 mt-6"><p className="font-semibold text-blue-700">Online Application</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Apply for {data.variant?.title || data.service.title}</h1><p className="mt-2 text-slate-600">Fill the details and upload the required documents on this single page.</p></header>{error && <p role="alert" className="mb-6 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<DynamicForm form={data.form} service={data.service} variant={data.variant} isSubmitting={isSubmitting} onSubmit={submit} /></section>;
};
export default ApplyService;
